const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const base=path.resolve(__dirname,'../../backend/consultation');const common=fs.readFileSync(path.join(base,'common.js'),'utf8');const stages=['authorize','classes','appointments','followup','summary'];const code=Object.fromEntries(stages.map(n=>[n,common+'\n'+fs.readFileSync(path.join(base,n+'.js'),'utf8').replace('// FAMILY_HANDLERS: build script inserts family.js here.',fs.readFileSync(path.join(base,'family.js'),'utf8'))]));
code.authorize+='\n'+fs.readFileSync(path.join(base,'referral.js'),'utf8');
function fixture(){const past=new Date(Date.now()-3600000).toISOString();return {account:[{id:101,username:'老师甲',wechat_nickname:'老师甲'},{id:102,username:'老师乙',wechat_nickname:'老师乙'},{id:201,username:'家长甲',wechat_nickname:'家长甲'},{id:202,username:'家长乙',wechat_nickname:'家长乙'},{id:203,username:'家长丙',wechat_nickname:'家长丙'}],service_provider:[{id:1,account_id:101,service_status:'ACTIVE',can_reply:true,can_accept_order:true},{id:2,account_id:102,service_status:'ACTIVE',can_reply:true,can_accept_order:true}],public_class:[{id:11,title:'甲公开课',product_kind:'COURSE',status:'PUBLISHED',organizer_id:1,starts_at:past,group_guide:'联系老师'},{id:12,title:'乙公开课',product_kind:'COURSE',status:'PUBLISHED',organizer_id:2,starts_at:past,group_guide:'联系老师'},{id:13,title:'草稿',product_kind:'COURSE',status:'DRAFT',organizer_id:1}],public_class_enrollment:[{id:21,customer_id:201,public_class_id:11,status:'REGISTERED',attendance_status:'ATTENDED',verified_by_id:1,verified_at:past},{id:22,customer_id:202,public_class_id:12,status:'REGISTERED',attendance_status:'PENDING'}],course_registration_order:[],course_referral:[],offline_appointment:[{id:31,customer_id:201,provider_id:1,enrollment_id:21,status:'CONFIRMED',confirmed_at:past,created_at:past,child_info:{name:'孩子甲'}},{id:32,customer_id:202,provider_id:2,enrollment_id:22,status:'PENDING'}],offline_consultation_record:[{id:41,appointment_id:31,author_id:1,status:'CONFIRMED',summary:'老师确认的记录',advice:[{key:'step-1',content:'每天倾听'}]}],consultation_feedback:[],consultation_feedback_reply:[],consultation_summary_job:[],consultation_session:[],consultation_message:[],fz_conversation:[],fz_message:[],fz_message_content:[]};}
function engine(db){db.public_class_enrollment.forEach(r=>{r.feedback_revision??=0;r.feedback_status??='NOT_SUBMITTED';});let next=1000;const calls=[],tasks=[];function related(table,row){const r={...row};if(table==='public_class_enrollment')r.public_class=db.public_class.find(c=>c.id===row.public_class_id);if(table==='course_referral'){r.referrer=db.account.find(a=>a.id===row.referrer_id);r.referred_account=db.account.find(a=>a.id===row.referred_account_id);if(r.referred_account)r.referred_account={...r.referred_account,public_class_enrollments:db.public_class_enrollment.filter(e=>e.customer_id===row.referred_account_id).map(e=>related('public_class_enrollment',e))};}if(table==='offline_appointment')r.provider=db.service_provider.find(p=>p.id===row.provider_id);if(table==='consultation_feedback')r.replies=db.consultation_feedback_reply.filter(p=>p.feedback_id===row.id);return r;}
function match(row,w){
 if(w._and)return w._and.every(v=>match(row,v));if(w._or)return w._or.some(v=>match(row,v));
 if(w._is_null){const operand=Object.values(w._is_null)[0];return row[operand.column]==null;}
 for(const op of ['_eq','_lt','_gt','_ilike'])if(w[op]){const pair=op==='_ilike'?w[op]:Object.values(w[op])[0],left=row[pair.left_operand.column],right=pair.right_operand.literal;if(op==='_eq')return String(left)===String(right);if(op==='_lt')return new Date(left).getTime()<new Date(right).getTime();if(op==='_gt')return new Date(left).getTime()>new Date(right).getTime();const query=String(right).slice(1,-1).replace(/\\([%_\\])/g,'$1');return String(left||'').toLowerCase().includes(query.toLowerCase());}
 return Object.entries(w).every(([key,value])=>row[key]&&match(row[key],value));
}
function runGql(name,q,vars,options){assert.equal(name, q.match(/^(?:query|mutation)\s+(\w+)/)[1]);assert.equal(options.role,"admin");calls.push({q,vars:structuredClone(vars),options});if(name==='AllocateRecording')return {filePresignedUrl:{fileId:8001,uploadUrl:'https://example.invalid/private-upload',uploadHeaders:{},contentType:'audio/mpeg'}};if(name==='SendRecording')return {fz_zai_send_ai_message:9001};if(name==='GenerateCourseMiniCode')return {wechatQRcodeWithParams:{type:'SUCCESS',image:{id:8002,url:'https://example.invalid/course-mini-code'}}};if(name==='CourseReferralAccount')return {rows:db.account.filter(row=>match(row,vars.where)).slice(0,1)};let m=q.match(/rows: (\w+)\(/);if(m){const table=m[1];if(table.endsWith('_aggregate'))return {rows:{aggregate:{count:db[table.slice(0,-10)].map(row=>related(table.slice(0,-10),row)).filter(row=>match(row,vars.where)).length}}};const limit=Number((q.match(/limit: (\d+)/)||[])[1]||100);return {data:{rows:(db[table]||[]).map(row=>related(table,row)).filter(row=>match(row,vars.where)).sort((a,b)=>b.id-a.id).slice(0,limit)}};}m=q.match(/saved: insert_(\w+)\(/);if(m){const table=m[1];const o=structuredClone(vars.object);const duplicate=db[table].find(r=>o.request_key?r.request_key===o.request_key:table==='public_class_enrollment'?r.customer_id===o.customer_id&&r.public_class_id===o.public_class_id:table==='course_referral'?r.referred_account_id===o.referred_account_id:table==='service_provider'?r.account_id===o.account_id:table==='offline_consultation_record'&&r.appointment_id===o.appointment_id);if(duplicate&&q.includes('on_conflict'))return {data:{saved:{affected_rows:0,returning:[]}}};const row={id:next++,...(table==='public_class_enrollment'?{feedback_revision:0,feedback_status:'NOT_SUBMITTED'}:{}),...o};db[table].push(row);return {data:{saved:{affected_rows:1,returning:[{id:row.id}]}}};}m=q.match(/saved: update_(\w+)\(/);if(m){const rows=db[m[1]].filter(r=>match(related(m[1],r),vars.where));rows.forEach(r=>Object.assign(r,structuredClone(vars.object)));return {data:{saved:{affected_rows:rows.length,returning:rows.map(r=>({id:r.id}))}}};}throw new Error('Unrecognized query '+q);}
function run(account,operation,payload={}){const snapshot=structuredClone(db);try{let state;for(const stage of stages){let output;const args=stage==='authorize'?{account_id:account,operation,payload}:{state};vm.runInNewContext(code[stage],{context:{getArg:k=>args[k],setReturn:(k,v)=>{output=structuredClone(v);},runGql,createActionFlowTask:(flow,version,args)=>tasks.push({flow,args})},Date,JSON,Number,String,Array,Object,Set,Error},{timeout:1000});state=output;}return state;}catch(error){for(const key of Object.keys(db))db[key]=snapshot[key];throw error;}}
return {run,calls,db,tasks,runGql};}
function rejectsNoWrites(account,op,payload,regexp){const db=fixture();const e=engine(db);const before=JSON.stringify(db);assert.throws(()=>e.run(account,op,payload),regexp);assert.equal(JSON.stringify(db),before);}
test('匿名只可读取尚未开始的公开课程，历史课程、问卷和草稿不泄露',()=>{const db=fixture();db.public_class.push({id:14,title:'未来公开课',product_kind:'COURSE',status:'PUBLISHED',organizer_id:1,starts_at:new Date(Date.now()+3600000).toISOString()},{id:15,title:'简易方案梳理',product_kind:'QUESTIONNAIRE',status:'PUBLISHED',organizer_id:1,starts_at:new Date(Date.now()+3600000).toISOString()});const e=engine(db);const r=e.run(null,'LIST_CLASSES');assert.deepEqual(r.data.classes.map(c=>c.id),[14]);assert.throws(()=>e.run(null,'GET_CLASS',{classId:15}),/专属问卷二维码/);rejectsNoWrites(null,'MY_OVERVIEW',{},/登录/);});
for(const op of ['SAVE_CLASS','VERIFY_ENROLLMENT','CONFIRM_APPOINTMENT','SAVE_RECORD','COMPLETE_APPOINTMENT','REPLY_FEEDBACK','STAFF_OVERVIEW'])test('普通客户不能伪造工作人员操作 '+op,()=>rejectsNoWrites(201,op,{providerId:1,account_id:101,role:'admin',id:11,appointmentId:31,feedbackId:1},/工作人员/));
for(const op of ['GET_APPOINTMENT','SAVE_CHILD_INFO','CANCEL_APPOINTMENT','SEND_FEEDBACK'])test('客户不能访问其他孩子 '+op,()=>rejectsNoWrites(202,op,{appointmentId:31,requestKey:'x'},/其他客户/));
for(const op of ['CONFIRM_APPOINTMENT','SAVE_RECORD','COMPLETE_APPOINTMENT'])test('老师不能处理未分配的咨询 '+op,()=>rejectsNoWrites(102,op,{appointmentId:31},/其他客户/));
test('实际参加为资格依据，伪造付费或到课字段不能绕过',()=>rejectsNoWrites(202,'CREATE_APPOINTMENT',{enrollmentId:21,attendance_status:'ATTENDED',paid:true,eligible:true,requestKey:'x',name:'家长',phone:'13800000000',requestedTime:'周六',concerns:'沟通'},/参加免费公开课/));
test('到课登记的课程归属也须校验',()=>rejectsNoWrites(101,'VERIFY_ENROLLMENT',{enrollmentId:22,attendanceStatus:'ATTENDED'},/本人公开课/));
test('未来课程不能提前核实参加',()=>{const db=fixture();db.public_class[0].starts_at=new Date(Date.now()+60000).toISOString();db.public_class_enrollment[0].attendance_status='PENDING';const e=engine(db);assert.throws(()=>e.run(101,'VERIFY_ENROLLMENT',{enrollmentId:21,attendanceStatus:'ATTENDED'}),/课程开始/);});
test('符合资格可申请，重复请求只产生一份待确认预约',()=>{const e=engine(fixture());const p={requestKey:'same',requestedTime:'周六下午',concerns:'沟通',name:'家长甲',phone:'13800000000'};const a=e.run(201,'CREATE_APPOINTMENT',p);const b=e.run(201,'CREATE_APPOINTMENT',p);assert.equal(a.data.id,b.data.id);assert.equal(e.db.offline_appointment.filter(x=>x.request_key).length,1);assert.equal(e.db.offline_appointment.at(-1).status,'PENDING');});
test('缺少人工核实证据不能申请',()=>{const db=fixture();db.public_class_enrollment[0].verified_at=null;const e=engine(db);assert.throws(()=>e.run(201,'CREATE_APPOINTMENT',{requestKey:'new'}),/核实/);});
test('不能从待确认阶段直接填写孩子资料',()=>rejectsNoWrites(202,'SAVE_CHILD_INFO',{appointmentId:32,childInfo:{}},/预约确认后/));
test('孩子信息严格白名单，写入不会改变归属和状态',()=>{const e=engine(fixture());e.run(201,'SAVE_CHILD_INFO',{appointmentId:31,childInfo:{name:'小甲',age:8,guardian:'家长',relationship:'母亲',phone:'13800000000',concerns:'学习沟通',customer_id:202,status:'COMPLETED'}});const a=e.db.offline_appointment[0];assert.equal(a.customer_id,201);assert.equal(a.status,'CONFIRMED');assert.equal(a.child_info.customer_id,undefined);assert.equal(a.child_info.name,'小甲');});
test('缺失年龄不能默认为0',()=>rejectsNoWrites(201,'SAVE_CHILD_INFO',{appointmentId:31,childInfo:{age:''}},/年龄/));
test('已确认记录不能被覆盖',()=>rejectsNoWrites(101,'SAVE_RECORD',{appointmentId:31,summary:'覆盖',confirm:true,advice:[]},/已确认/));
test('不存在的建议不能反馈',()=>rejectsNoWrites(201,'SEND_FEEDBACK',{appointmentId:31,adviceKey:'forged',content:'反馈',requestKey:'x'},/已确认的执行建议/));
test('咨询完成后仍可反馈，反馈及回复均幂等保留',()=>{const e=engine(fixture());e.db.offline_appointment[0].status='COMPLETED';const p={appointmentId:31,adviceKey:'step-1',content:'今天耐心听完了',requestKey:'one'};e.run(201,'SEND_FEEDBACK',p);e.run(201,'SEND_FEEDBACK',p);assert.equal(e.db.consultation_feedback.length,1);const f=e.db.consultation_feedback[0];const r={feedbackId:f.id,content:'继续坚持',requestKey:'reply'};e.run(101,'REPLY_FEEDBACK',r);e.run(101,'REPLY_FEEDBACK',r);assert.equal(e.db.consultation_feedback_reply.length,1);assert.equal(f.status,'REPLIED');});
test('另一个老师无法回复反馈',()=>{const e=engine(fixture());e.db.consultation_feedback.push({id:51,appointment_id:31});assert.throws(()=>e.run(102,'REPLY_FEEDBACK',{feedbackId:51,content:'不属于你',requestKey:'x'}),/其他客户/);assert.equal(e.db.consultation_feedback_reply.length,0);});
test('查询本人记录，不因payload customerId切换身份',()=>{const e=engine(fixture());const r=e.run(201,'MY_OVERVIEW',{customerId:202});assert.deepEqual(r.data.appointments.map(a=>a.id),[31]);});
test('未知操作与超长正文拒绝',()=>{rejectsNoWrites(201,'RUN_SQL',{query:'delete from account'},/不支持/);rejectsNoWrites(201,'SEND_FEEDBACK',{appointmentId:31,adviceKey:'step-1',content:'x'.repeat(6001),requestKey:'x'},/过长/);});
test('查询表白名单及无单条记录条件的修改被拒绝',()=>{for(const snippet of ['list("account", {}, "password", 1)','update("offline_appointment", {}, {status:"COMPLETED"})','insert("service_provider", {can_reply:true})'])assert.throws(()=>vm.runInNewContext(common+'\n'+snippet,{context:{runGql:()=>{throw new Error('Should not reach database')}}}),/不允许访问|限定单条/);});
module.exports={engine,fixture};

test('本次留言在建议确认前可用，仍隔离其他咨询',()=>{const e=engine(fixture());e.db.offline_consultation_record=[];e.run(201,'SEND_NOTE',{appointmentId:31,content:'想沟通学习压力',requestKey:'note'});assert.equal(e.db.consultation_feedback[0].advice_key,'conversation');assert.throws(()=>e.run(202,'SEND_NOTE',{appointmentId:31,content:'越权',requestKey:'x'}),/其他客户/);});
test('文字总结只取本次沟通，忽略伪造的transcript和归属',()=>{const e=engine(fixture());e.db.consultation_feedback.push({id:61,appointment_id:31,content:'本次内容'},{id:62,appointment_id:32,content:'其他孩子秘密'});e.run(201,'SUMMARIZE_TEXT',{appointmentId:31,requestKey:'text',transcript:'伪造内容',customerId:202});const j=e.db.consultation_summary_job[0];assert.equal(j.transcript,'家长：本次内容');assert.equal(j.requester_id,201);assert.equal(e.tasks.length,1);});
test('空对话不创建总结任务',()=>rejectsNoWrites(201,'SUMMARIZE_TEXT',{appointmentId:31,requestKey:'text'},/还没有文字/));
test('跨账号无法发起录音上传，未同意无法分配文件',()=>{rejectsNoWrites(202,'PREPARE_RECORDING',{appointmentId:31},/其他客户/);rejectsNoWrites(201,'PREPARE_RECORDING',{appointmentId:31,requestKey:'audio'},/同意时间/);});
test('录音文件只接受服务器分配的id，不接受客户端fileId',()=>{const e=engine(fixture());e.run(201,'PREPARE_RECORDING',{appointmentId:31,requestKey:'audio',consentedAt:new Date().toISOString(),sizeBytes:1234,md5Base64:'AAAAAAAAAAAAAAAAAAAAAA==',fileId:9999});const j=e.db.consultation_summary_job[0];assert.equal(j.recording_id,8001);assert.equal(j.status,'UPLOADING');assert.ok(e.calls.some(c=>c.q.includes('acl:PRIVATE')));});
test('不能挪用他人的录音任务',()=>{const e=engine(fixture());e.db.consultation_summary_job.push({id:71,appointment_id:31,requester_id:101,source:'AUDIO',recording_id:8001,consented_at:new Date().toISOString(),status:'UPLOADING'});assert.throws(()=>e.run(201,'PROCESS_RECORDING',{appointmentId:31,jobId:71}),/自己提交/);assert.equal(e.tasks.length,0);});
test('上传处理重复提交只创建一次异步任务',()=>{const e=engine(fixture());e.db.consultation_summary_job.push({id:71,appointment_id:31,requester_id:201,source:'AUDIO',recording_id:8001,consented_at:new Date().toISOString(),status:'UPLOADING'});e.run(201,'PROCESS_RECORDING',{appointmentId:31,jobId:71});e.run(201,'PROCESS_RECORDING',{appointmentId:31,jobId:71});assert.equal(e.tasks.length,1);});
test('异步准备再次核对登录人，不信任jobId',()=>{const e=engine(fixture());e.db.consultation_summary_job.push({id:71,appointment_id:31,requester_id:201,status:'QUEUED',source:'TEXT',transcript:'沟通'});const script=common+'\n'+fs.readFileSync(path.join(base,'summary-prepare.js'),'utf8');assert.throws(()=>vm.runInNewContext(script,{context:{getArg:k=>({account_id:202,job_id:71})[k],runGql:e.runGql}}),/其他账号/);assert.equal(e.db.consultation_summary_job[0].status,'QUEUED');});
test('客户不能直接提交AI草稿作为已确认记录',()=>rejectsNoWrites(201,'SAVE_RECORD',{appointmentId:31,summary:'伪造AI',confirm:true},/工作人员权限/));

test('旧的异步结果不能覆盖重试中的新任务',()=>{const e=engine(fixture());e.db.consultation_summary_job.push({id:71,appointment_id:31,requester_id:201,status:'PROCESSING',conversation_ref:'attempt:new'});const script=common+'\n'+fs.readFileSync(path.join(base,'summary-save.js'),'utf8');assert.throws(()=>vm.runInNewContext(script,{context:{getArg:k=>({state:{jobId:71,requesterId:201,attempt:'attempt:old'},draft:'迟到结果',conversation_id:9001})[k],runGql:e.runGql}}),/状态已变化/);assert.equal(e.db.consultation_summary_job[0].conversation_ref,'attempt:new');});

function courseFixture(){const db=fixture();db.public_class_enrollment=[];db.public_class.forEach(c=>Object.assign(c,{revision:0,reserved_count:0,capacity:1,city:'成都',starts_at:new Date(Date.now()+3600000).toISOString()}));return db;}
function signup(e,account=201,classId=11){return e.run(account,'ENROLL',{classId,name:'合成家长',phone:'13800000000'}).data.enrollment;}
test('登录不锁定，首次成功报名锁定，取消及新链接不改绑',()=>{
 const e=engine(courseFixture());assert.equal(e.run(202,'LOCK_REFERRER',{referrerId:101}).data.locked,false);assert.equal(e.db.course_referral.length,0);
 const first=e.run(202,'ENROLL',{classId:11,name:'家长',phone:'13800000000',referrerId:101}).data.enrollment;
 assert.equal(e.db.course_referral[0].referrer_id,101);e.run(202,'CANCEL_ENROLLMENT',{enrollmentId:first.id});
 e.run(202,'ENROLL',{classId:11,name:'家长',phone:'13800000000',referrerId:102});assert.equal(e.db.course_referral.length,1);assert.equal(e.db.course_referral[0].referrer_id,101);
});
test('推荐人只能查看自己的直属客户；普通客户不能邀请或读取名单',()=>{
 const e=engine(courseFixture());e.run(202,'ENROLL',{classId:11,name:'甲',phone:'13800000000',referrerId:101});e.run(203,'ENROLL',{classId:12,name:'乙',phone:'13800000000',referrerId:102});
 assert.deepEqual(e.run(101,'MY_REFERRALS').data.items.map(x=>x.referred_account_id),[202]);assert.throws(()=>e.run(201,'MY_REFERRALS'),/代理权限/);
 assert.throws(()=>e.run(201,'REFERRAL_CANDIDATE',{referrerId:202}),/邀请权限/);
});
test('报名重复提交不占双份名额，满员不能超额',()=>{const e=engine(courseFixture());const first=signup(e);const again=signup(e);assert.equal(first.id,again.id);assert.equal(e.db.public_class[0].reserved_count,1);assert.throws(()=>signup(e,202),/名额已满/);assert.equal(e.db.public_class_enrollment.length,1);});
test('取消报名释放名额，重新报名换码并使旧码失效',()=>{const e=engine(courseFixture());const first=signup(e);e.run(201,'CANCEL_ENROLLMENT',{enrollmentId:first.id});e.run(201,'CANCEL_ENROLLMENT',{enrollmentId:first.id});assert.equal(e.db.public_class[0].reserved_count,0);assert.equal(e.db.public_class_enrollment[0].entry_code,null);const second=signup(e);assert.equal(second.id,first.id);assert.notEqual(second.entry_code,first.entry_code);assert.equal(e.db.public_class[0].reserved_count,1);assert.throws(()=>e.run(101,'LOOKUP_ENTRY',{classId:11,entryCode:first.entry_code}),/入场码无效/);});
test('报名必须在报名截止前，不受伪造状态影响',()=>{const db=courseFixture();db.public_class[0].registration_closes_at=new Date(Date.now()-1).toISOString();const e=engine(db);assert.throws(()=>e.run(201,'ENROLL',{classId:11,name:'家长',phone:'13800000000',status:'ATTENDED',capacity:999}),/截止/);assert.equal(e.db.public_class_enrollment.length,0);});
test('付费课程金额由后端返回，未完成真实支付不能绕过报名',()=>{const db=courseFixture();db.public_class[0].registration_fee=100;const e=engine(db);const detail=e.run(null,'GET_CLASS',{classId:11}).data.classInfo;assert.equal(detail.registration_fee,100);assert.throws(()=>e.run(201,'ENROLL',{classId:11,name:'家长',phone:'13800000000',paid:true,price:0}),/需先完成缴费/);assert.equal(e.db.public_class_enrollment.length,0);assert.equal(e.db.public_class[0].reserved_count,0);});
test('客户不能访问或取消别人的入场凭证',()=>{const e=engine(courseFixture());const first=signup(e);for(const op of ['GET_ENROLLMENT','CANCEL_ENROLLMENT'])assert.throws(()=>e.run(202,op,{enrollmentId:first.id}),/其他客户/);assert.equal(e.db.public_class[0].reserved_count,1);});
test('扫码必须匹配本场和负责老师，读取不授予资格',()=>{const e=engine(courseFixture());const first=signup(e);assert.throws(()=>e.run(102,'LOOKUP_ENTRY',{classId:11,entryCode:first.entry_code}),/本人负责/);assert.throws(()=>e.run(102,'LOOKUP_ENTRY',{classId:12,entryCode:first.entry_code}),/不属于本场/);const found=e.run(101,'LOOKUP_ENTRY',{classId:11,entryCode:'EMPATH-ENTRY:'+first.entry_code}).data.enrollment;assert.equal(found.id,first.id);assert.equal(e.run(201,'MY_OVERVIEW').data.eligible,false);});
test('实际到课才开通资格，扫码核销重复提交不改核实时间',()=>{const e=engine(courseFixture());const first=signup(e);e.db.public_class[0].starts_at=new Date(Date.now()-1000).toISOString();const args={classId:11,entryCode:'EMPATH-ENTRY:'+first.entry_code};e.run(101,'CHECK_IN',args);const when=e.db.public_class_enrollment[0].verified_at;assert.equal(e.db.public_class_enrollment[0].checkin_method,'QR');assert.equal(e.run(201,'MY_OVERVIEW').data.eligible,true);assert.equal(e.run(101,'CHECK_IN',args).data.alreadyCheckedIn,true);assert.equal(e.db.public_class_enrollment[0].verified_at,when);assert.throws(()=>e.run(101,'VERIFY_ENROLLMENT',{enrollmentId:first.id,attendanceStatus:'ABSENT'}),/不能改/);assert.throws(()=>e.run(201,'CANCEL_ENROLLMENT',{enrollmentId:first.id}),/已到课/);});
test('签到时间窗和取消状态在后端强制校验',()=>{const e=engine(courseFixture());const first=signup(e);assert.throws(()=>e.run(101,'CHECK_IN',{classId:11,entryCode:first.entry_code}),/课程开始/);e.db.public_class[0].starts_at=new Date(Date.now()-10000).toISOString();e.db.public_class[0].checkin_closes_at=new Date(Date.now()-1000).toISOString();assert.throws(()=>e.run(101,'CHECK_IN',{classId:11,entryCode:first.entry_code}),/签到时间已结束/);e.db.public_class_enrollment[0].status='CANCELED';assert.throws(()=>e.run(101,'VERIFY_ENROLLMENT',{enrollmentId:first.id,attendanceStatus:'ATTENDED'}),/已取消/);});
test('名单计数限定本场，客户与其他老师不能读取',()=>{const e=engine(courseFixture());signup(e);signup(e,202,12);const r=e.run(101,'COURSE_ROSTER',{classId:11}).data;assert.deepEqual(r.stats,{registered:1,attended:0,pending:1});assert.equal(r.items.length,1);assert.throws(()=>e.run(201,'COURSE_ROSTER',{classId:11}),/工作人员/);assert.throws(()=>e.run(102,'COURSE_ROSTER',{classId:11}),/本人负责/);assert.equal(e.run(101,'COURSE_ROSTER',{classId:11,search:'无匹配'}).data.items.length,0);});
test('报名列表分页完整、无重复且不能指定他人身份',()=>{const db=courseFixture();for(let i=1;i<=45;i++)db.public_class_enrollment.push({id:100+i,customer_id:201,public_class_id:11,status:'REGISTERED',attendance_status:'PENDING'});db.public_class_enrollment.push({id:999,customer_id:202,public_class_id:12,status:'REGISTERED'});const e=engine(db);const ids=[];let cursor;do{const r=e.run(201,'MY_ENROLLMENTS',{cursor,customerId:202}).data;ids.push(...r.items.map(x=>x.id));cursor=r.nextCursor;}while(cursor);assert.equal(ids.length,45);assert.equal(new Set(ids).size,45);assert.ok(!ids.includes(999));});
test('修改课程校验已报名人数及版本，不能覆盖并发修改',()=>{const e=engine(courseFixture());signup(e);const c=e.db.public_class[0],args={id:11,title:'公开课',groupGuide:'联系老师',startsAt:c.starts_at,status:'PUBLISHED',capacity:1,revision:0};assert.throws(()=>e.run(101,'SAVE_CLASS',args),/已被更新/);assert.equal(e.db.public_class[0].title,'甲公开课');});
test('旧报名首次读取生成入场码，后续稳定',()=>{const e=engine(courseFixture());e.db.public_class_enrollment.push({id:99,customer_id:201,public_class_id:11,status:'REGISTERED',attendance_status:'PENDING',entry_code:null});const a=e.run(201,'GET_ENROLLMENT',{enrollmentId:99}).data.enrollment;const b=e.run(201,'GET_ENROLLMENT',{enrollmentId:99}).data.enrollment;assert.match(a.entry_code,/^[A-Z2-9]{24}$/);assert.equal(a.entry_code,b.entry_code);});
test('公开详情不返回进群材料，已报名者可以读取自己的指引',()=>{const e=engine(courseFixture());assert.equal(e.run(null,'GET_CLASS',{classId:11}).data.classInfo.group_guide,undefined);signup(e);assert.equal(e.run(201,'GET_CLASS',{classId:11}).data.classInfo.group_guide,'联系老师');assert.equal(e.run(202,'GET_CLASS',{classId:11}).data.enrollment,null);});

test('不限名额兼容数字和字符串零',()=>{const db=courseFixture();db.public_class[0].capacity='0';const e=engine(db);signup(e);signup(e,202);assert.equal(e.db.public_class[0].reserved_count,2);assert.equal(e.run(null,'GET_CLASS',{classId:11}).data.classInfo.remaining,null);});

test('原生页面提交的实际参数可完成发布、报名、凭证读取和核销',async()=>{
 const db=courseFixture(),e=engine(db),navigation=[];let actor=101,scanResult='',modalTask;
 const service={...require('../../utils/consultationService'),call:async(op,p={})=>e.run(actor,op,p).data,error:(p,x)=>p.setData({error:x.message})};
 const wx={navigateTo:r=>navigation.push(r.url),redirectTo:r=>navigation.push(r.url),showToast:()=>{},showModal:r=>{modalTask=r.success({confirm:true});},scanCode:r=>{modalTask=r.success({result:scanResult});},createCanvasContext:()=>({setFillStyle(){},fillRect(){},draw(_,done){done();}})};
 const qr=require('../../utils/courseQr');
 function page(name){let result;const source=fs.readFileSync(path.resolve(base,'../../pages',name,name+'.js'),'utf8');vm.runInNewContext(source,{Page:p=>result=p,require:r=>r.includes('consultationService')?service:r.includes('/auth')?{requireLogin:()=>true,isLoggedIn:()=>true}:r.includes('coursePresentation')?require('../../utils/coursePresentation'):r.includes('courseQr')?{draw:()=>Promise.resolve(qr.matrix(scanResult))}:r.includes('loginReturn')?{takeEnrollmentForm:()=>null,restore:()=>false}:{},wx,Date,encodeURIComponent,decodeURIComponent});result.data=structuredClone(result.data);result.setData=function(values,done){for(const[k,v]of Object.entries(values)){const parts=k.split('.');let target=this.data;for(const part of parts.slice(0,-1))target=target[part];target[parts.at(-1)]=v;}if(done)done();};return result;}
 const edit=page('course-edit');await edit.refresh();assert.equal(edit.data.allowed,true);const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);edit.setData({form:{...edit.data.form,title:'页面参数联调课程',date:tomorrow,time:'18:00',groupGuide:'工作人员邀请进群',capacity:'10',registrationFee:'0',city:'成都'}});await edit.submit('PUBLISHED');assert.equal(edit.data.error,'');const classId=edit.classId;assert.ok(classId);assert.equal(db.public_class.find(c=>c.id===classId).capacity,10);
 actor=201;const enroll=page('class-enroll');enroll.onLoad({id:String(classId)});await enroll.refresh();enroll.input({currentTarget:{dataset:{key:'name'}},detail:{value:'合成家长'}});enroll.input({currentTarget:{dataset:{key:'phone'}},detail:{value:'13800000000'}});await enroll.submit();assert.equal(enroll.data.error,'');const row=db.public_class_enrollment[0];assert.ok(navigation.at(-1).includes('/class-ticket?id='+row.id));
 scanResult='EMPATH-ENTRY:'+row.entry_code;const ticket=page('class-ticket');ticket.onLoad({id:String(row.id)});await ticket.refresh();assert.equal(ticket.data.enrollment.entryPayload,scanResult);assert.equal(ticket.data.enrollment.phoneMasked,'138****0000');
 actor=101;const roster=page('course-roster');roster.onLoad({id:String(classId)});await roster.refresh();assert.equal(roster.data.stats.registered,1);roster.scan();await modalTask;assert.equal(roster.data.scanCandidate.id,row.id);assert.equal(db.public_class_enrollment[0].attendance_status,'PENDING');
 db.public_class.find(c=>c.id===classId).starts_at=new Date(Date.now()-1000).toISOString();let checkinTask;const perform=roster.perform.bind(roster);roster.perform=(...args)=>(checkinTask=perform(...args));roster.confirmScan();await checkinTask;assert.equal(roster.data.error,'');assert.equal(roster.data.stats.attended,1);assert.equal(db.public_class_enrollment[0].checkin_method,'QR');
 actor=201;await ticket.refresh();assert.equal(ticket.data.enrollment.stateText,'已参加');assert.equal(e.run(201,'MY_OVERVIEW').data.eligible,true);
});
test('报名分享码由负责老师生成，绑定实际详情路径和场次，已有图片可复用',()=>{const e=engine(courseFixture());assert.equal(e.run(101,'GET_CLASS',{classId:11}).data.canManage,true);assert.equal(e.run(201,'GET_CLASS',{classId:11}).data.canManage,false);assert.throws(()=>e.run(201,'GENERATE_CLASS_SHARE_CODE',{classId:11}),/工作人员/);assert.throws(()=>e.run(102,'GENERATE_CLASS_SHARE_CODE',{classId:11}),/本人负责/);assert.throws(()=>e.run(101,'GENERATE_CLASS_SHARE_CODE',{classId:13}),/先发布/);const r=e.run(101,'GENERATE_CLASS_SHARE_CODE',{classId:11}).data;assert.equal(r.image.id,8002);const generation=e.calls.filter(c=>c.q.includes('query GenerateCourseMiniCode'));assert.equal(generation.length,1);assert.equal(generation[0].vars.input.page,'pages/public-class-detail/public-class-detail');assert.deepEqual(generation[0].vars.input.args,{id:'11'});assert.equal(e.db.public_class[0].share_code_id,8002);e.db.public_class[0].share_code=r.image;e.run(101,'GENERATE_CLASS_SHARE_CODE',{classId:11});assert.equal(e.calls.filter(c=>c.q.includes('query GenerateCourseMiniCode')).length,1);});

test('本人和负责老师可完整翻阅超过旧上限的预约，不能借游标读取他人预约',()=>{
 const db=fixture();for(let i=0;i<245;i++)db.offline_appointment.push({id:1000+i,customer_id:201,provider_id:1,status:'COMPLETED'});
 db.offline_appointment.push({id:9000,customer_id:202,provider_id:2,status:'PENDING'});const e=engine(db);
 for(const [actor,op] of [[201,'MY_OVERVIEW'],[101,'STAFF_OVERVIEW']]){let cursor=null,ids=[];do{const r=e.run(actor,op,{paginate:true,appointmentCursor:cursor,customerId:202,providerId:2}).data;assert.ok(r.appointments.length<=20);ids.push(...r.appointments.map(a=>a.id));cursor=r.nextAppointmentCursor;}while(cursor);assert.equal(ids.length,246);assert.equal(new Set(ids).size,246);assert.ok(!ids.includes(9000));}
});
test('咨询反馈和总结可完整分页，游标不改变咨询归属及总结请求人范围',()=>{
 const db=fixture();for(let i=0;i<225;i++)db.consultation_feedback.push({id:1000+i,appointment_id:31,content:'反馈'+i,replies:[]});
 for(let i=0;i<45;i++)db.consultation_summary_job.push({id:2000+i,appointment_id:31,requester_id:201,status:'READY',draft:'总结'+i});
 db.consultation_feedback.push({id:9000,appointment_id:32,content:'其他咨询'});db.consultation_summary_job.push({id:9000,appointment_id:31,requester_id:101,status:'READY'});const e=engine(db);
 for(const [key,cursorKey,nextKey,n] of [['feedbacks','feedbackCursor','nextFeedbackCursor',225],['summaryJobs','summaryCursor','nextSummaryCursor',45]]){let cursor=null,ids=[];do{const r=e.run(201,'GET_APPOINTMENT',{paginate:true,appointmentId:31,[cursorKey]:cursor}).data;ids.push(...r[key].map(x=>x.id));cursor=r[nextKey];}while(cursor);assert.equal(ids.length,n);assert.equal(new Set(ids).size,n);assert.ok(!ids.includes(9000));}
 assert.throws(()=>e.run(202,'GET_APPOINTMENT',{appointmentId:31,feedbackCursor:9001}),/其他客户/);
});

test('旧版客户端未启用分页时保留原有条数，避免同步后端后截短旧界面',()=>{const db=fixture();for(let i=0;i<240;i++)db.offline_appointment.push({id:1000+i,customer_id:201,provider_id:1});const e=engine(db);assert.equal(e.run(201,'MY_OVERVIEW').data.appointments.length,100);assert.equal(e.run(101,'STAFF_OVERVIEW').data.appointments.length,200);assert.equal(e.run(201,'MY_OVERVIEW',{paginate:true}).data.appointments.length,20);});

function childForm(extra={}){return {enrollmentId:21,name:'合成孩子',gender:'女',age:12,grade:'六年级',economicSource:'父母供养',issues:['亲子沟通','学习动力'],description:'合成测试描述',dailyBehavior:'合成日常表现',guardianName:'合成家长',guardianPhone:'13800000000',consent:true,...extra};}
test('19.9问卷只通过有效管理或代理邀请开放，且不进入课程列表',()=>{
 const db=fixture();db.service_provider.push({id:3,account_id:203,display_name:'代理丙',service_kind:'AGENT',service_status:'ACTIVE',can_reply:false,can_accept_order:false});db.public_class.push({id:15,title:'简易方案梳理',description:'2026问卷梳理',product_kind:'QUESTIONNAIRE',status:'PUBLISHED',organizer_id:1,registration_fee:19.9,starts_at:'2099-12-31T12:00:00.000Z'});db.public_class_enrollment=[];
 const e=engine(db);assert.throws(()=>e.run(null,'GET_QUESTIONNAIRE',{}),/管理或代理/);const offer=e.run(null,'GET_QUESTIONNAIRE',{referrerId:203}).data;assert.equal(offer.offer.price,19.9);assert.equal(offer.offer.inviterName,'代理丙');assert.equal(offer.enrollment,null);assert.equal(e.run(null,'LIST_CLASSES').data.classes.some(c=>c.id===15),false);assert.throws(()=>e.run(201,'ENROLL',{classId:15,name:'家长',phone:'13800000000'}),/专属问卷二维码/);
});
// 业务类型是后加的字段：没有回填的老课程必须继续当成课程，不能因为问卷改动从首页、课程管理和我的报名里消失。
test('尚未标注业务类型的历史课程仍然是课程，不受问卷过滤影响',()=>{
 const db=fixture();const future=new Date(Date.now()+3600000).toISOString();
 db.public_class.push({id:16,title:'历史遗留公开课',status:'PUBLISHED',organizer_id:1,starts_at:future,group_guide:'联系老师'});
 db.public_class_enrollment.push({id:26,customer_id:201,public_class_id:16,status:'REGISTERED',attendance_status:'PENDING'});
 const e=engine(db);
 assert.equal(e.run(null,'LIST_CLASSES').data.classes.some(c=>c.id===16),true);
 assert.equal(e.run(101,'STAFF_CLASSES').data.classes.some(c=>c.id===16),true);
 assert.equal(e.run(201,'MY_ENROLLMENTS').data.items.some(r=>r.id===26),true);
 assert.equal(e.run(201,'MY_OVERVIEW').data.enrollments.some(r=>r.id===26),true);
 assert.equal(e.run(101,'STAFF_OVERVIEW').data.classes.some(c=>c.id===16),true);
 assert.ok(e.run(null,'GET_CLASS',{classId:16}).data.classInfo);
});
test('代理仅由管理人员指定，不能提升成工作人员，也不能覆盖已有工作人员',()=>{
 const e=engine(fixture());assert.throws(()=>e.run(201,'SET_AGENT',{accountId:202,active:true,role:'MANAGER'}),/工作人员/);
 e.run(101,'SET_AGENT',{accountId:203,active:true,can_reply:true});const row=e.db.service_provider.find(r=>r.account_id===203);assert.equal(row.service_kind,'AGENT');assert.equal(row.can_reply,false);assert.equal(row.can_accept_order,false);
 assert.equal(e.run(203,'FAMILY_OVERVIEW').data.role,'AGENT');assert.throws(()=>e.run(203,'STAFF_CHILD_INTAKES'),/工作人员/);assert.throws(()=>e.run(203,'SET_AGENT',{accountId:201,active:true}),/工作人员/);
 assert.throws(()=>e.run(101,'SET_AGENT',{accountId:102,active:true}),/身份不能/);e.run(101,'SET_AGENT',{accountId:203,active:false});assert.equal(e.run(203,'FAMILY_OVERVIEW').data.role,'CUSTOMER');assert.throws(()=>e.run(203,'MY_REFERRALS'),/代理权限/);
});
test('无推荐的老报名不能通过再次报名被划到代理名下；失败报名不锁定',()=>{
 const e=engine(courseFixture());signup(e,201);e.run(201,'ENROLL',{classId:12,name:'家长',phone:'13800000000',referrerId:101});assert.equal(e.db.course_referral.length,0);
 assert.throws(()=>e.run(202,'ENROLL',{classId:11,name:'家长',phone:'13800000000',referrerId:101}),/名额/);assert.equal(e.db.course_referral.length,0);
});
test('孩子表单要求恰好两个不同的有效问题、监护人同意、有效年龄和手机号',()=>{
 for(const extra of [{issues:['学习动力']},{issues:['学习动力','亲子沟通','手机与网络']},{issues:['学习动力','学习动力']},{issues:['伪造选项','学习动力']},{consent:false},{age:''},{age:-1},{guardianPhone:'123'}]){const e=engine(fixture());assert.throws(()=>e.run(201,'SUBMIT_CHILD_INTAKE',childForm(extra)));assert.equal(e.db.public_class_enrollment[0].child_submitted_at,undefined);}
 const e=engine(fixture());const r=e.run(201,'SUBMIT_CHILD_INTAKE',childForm({feedback_content:'伪造',feedback_status:'CONFIRMED'})).data.intake;assert.equal(r.feedback_status,'PENDING');assert.equal(r.feedback_available_at,undefined);assert.equal(r.feedback_content,undefined);assert.ok(r.guardian_consent_at);assert.throws(()=>e.run(201,'SUBMIT_CHILD_INTAKE',childForm()),/已提交/);
});
test('孩子资料只归本人和课程负责工作人员，邀请代理没有孩子资料权限',()=>{
 const e=engine(fixture());e.run(101,'SET_AGENT',{accountId:203,active:true});
 for(const actor of [null,202,102,203])assert.throws(()=>e.run(actor,'GET_CHILD_INTAKE',{enrollmentId:21}),/登录|其他客户/);
 assert.throws(()=>e.run(101,'SUBMIT_CHILD_INTAKE',childForm()),/仅家长本人/);e.run(201,'SUBMIT_CHILD_INTAKE',childForm());
 assert.deepEqual(e.run(101,'STAFF_CHILD_INTAKES').data.items.map(r=>r.id),[21]);assert.deepEqual(e.run(102,'STAFF_CHILD_INTAKES').data.items,[]);
 assert.throws(()=>e.run(202,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:1,content:'越权',confirm:true}),/其他客户/);
 assert.throws(()=>e.run(102,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:1,content:'越权',confirm:true}),/其他客户/);
});
test('草稿不开放正文，管理可设置查看时间，客户到点后才能读取',()=>{
 const e=engine(fixture());e.run(201,'SUBMIT_CHILD_INTAKE',childForm());
 e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:1,content:'工作人员草稿',confirm:false});let row=e.db.public_class_enrollment[0];assert.equal(row.feedback_confirmed_at,undefined);assert.equal(row.feedback_available_at,undefined);
 const beforeCalls=e.calls.length;const pending=e.run(201,'GET_CHILD_INTAKE',{enrollmentId:21}).data.intake;assert.equal(pending.feedback_content,undefined);assert.equal(pending.canViewFeedback,false);assert.equal(e.calls.slice(beforeCalls).some(c=>c.q.includes('feedback_content')),false);
 assert.throws(()=>e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:1,content:'过期草稿'}),/已更新/);
 assert.throws(()=>e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:2,content:'无时间',confirm:true}),/可查看回复的时间/);
 assert.throws(()=>e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:2,content:'过去时间',confirm:true,availableAt:'2000-01-01T00:00:00.000Z'}),/不能早于/);
 const before=Date.now(),chosen=new Date(before+21600000).toISOString();e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:2,content:'工作人员完成梳理',confirm:true,availableAt:chosen});
 row=e.db.public_class_enrollment[0];assert.ok(Date.parse(row.feedback_confirmed_at)>=before);assert.equal(row.feedback_available_at,chosen);assert.equal(e.run(201,'GET_CHILD_INTAKE',{enrollmentId:21}).data.intake.feedback_content,undefined);
 assert.throws(()=>e.run(101,'SAVE_CHILD_FEEDBACK',{enrollmentId:21,revision:3,content:'覆盖',confirm:true}),/已确认/);
 // Frozen-clock boundary verifies exact release and malformed timestamp rejection.
 const script=common+'\n'+fs.readFileSync(path.join(base,'family.js'),'utf8')+'\nreleased(sample)';const at=Date.parse(row.feedback_available_at);
 const canRead=(now,sample=row)=>vm.runInNewContext(script,{s:{},p:{},op:'TEST',Date:class extends Date{static now(){return now;}},sample});
 assert.equal(canRead(at-1),false);assert.equal(canRead(at),true);assert.equal(canRead(at,{...row,feedback_available_at:new Date(Date.parse(row.feedback_confirmed_at)-1).toISOString()}),false);
 row=e.db.public_class_enrollment[0];row.feedback_confirmed_at=new Date(Date.now()-1000).toISOString();row.feedback_available_at=new Date(Date.now()-1).toISOString();assert.equal(e.run(201,'GET_CHILD_INTAKE',{enrollmentId:21}).data.intake.feedback_content,'工作人员完成梳理');
});
test('代理身份即使错误携带工作人员能力也不能越权',()=>{const db=fixture();db.service_provider.push({id:3,account_id:203,service_kind:'AGENT',service_status:'ACTIVE',can_reply:true,can_accept_order:true});const e=engine(db);assert.equal(e.run(203,'FAMILY_OVERVIEW').data.role,'AGENT');assert.throws(()=>e.run(203,'SET_AGENT',{accountId:201,active:true}),/工作人员/);assert.throws(()=>e.run(203,'STAFF_CHILD_INTAKES'),/工作人员/);});
test('仅管理人员可直接绑定未归属客户，同代理重复绑定幂等，已有归属不可改绑',()=>{
 const e=engine(fixture());e.run(101,'SET_AGENT',{accountId:203,active:true});assert.throws(()=>e.run(201,'BIND_CUSTOMER',{customerId:202,agentAccountId:203}),/工作人员/);assert.throws(()=>e.run(203,'BIND_CUSTOMER',{customerId:202,agentAccountId:203}),/工作人员/);
 const r=e.run(101,'BIND_CUSTOMER',{customerId:202,agentAccountId:203}).data.binding;assert.equal(r.source,'MANAGER_ASSIGNED');assert.equal(r.referrer_id,203);e.run(101,'BIND_CUSTOMER',{customerId:202,agentAccountId:203});assert.equal(e.db.course_referral.length,1);
 e.run(101,'SET_AGENT',{accountId:201,active:true});assert.throws(()=>e.run(101,'BIND_CUSTOMER',{customerId:202,agentAccountId:201}),/不能改绑/);assert.throws(()=>e.run(101,'BIND_CUSTOMER',{customerId:203,agentAccountId:203}),/自己/);assert.throws(()=>e.run(101,'BIND_CUSTOMER',{customerId:102,agentAccountId:203}),/只能将客户/);
 assert.equal(e.run(101,'MANAGED_CUSTOMER_REFERRAL',{customerId:202}).data.binding.referrer_id,203);assert.throws(()=>e.run(202,'MANAGED_CUSTOMER_REFERRAL',{customerId:202}),/工作人员/);
});
