const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const {engine,fixture}=require('./consultation-security.test');
const relay=require('../../server/h5/course-payment');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'../..',f),'utf8');
const digest=read('utils/md5.js').replace('module.exports = { md5Base64 };','');
const source=read('backend/consultation/common.js')+'\n'+read('backend/consultation/classes.js').replace('// FAMILY_HANDLERS: build script inserts family.js here.',read('backend/consultation/family.js')).replace('// PAYMENT_HANDLERS: build script inserts course-payment.js and MD5 here.',digest+'\n'+read('backend/consultation/course-payment.js'));
const KEY='0123456789abcdef0123456789abcdef';
function signature(o){return crypto.createHash('md5').update(Object.keys(o).filter(k=>k!=='sign'&&o[k]!==''&&o[k]!=null).sort().map(k=>k+'='+o[k]).join('&')+'&key='+KEY).digest('hex').toUpperCase();}
function setup(){const db=fixture();db.course_registration_order=[];db.account.find(x=>x.id===201).username='wxh5_test';db.account.find(x=>x.id===201).wechat_openid='openid-test';db.public_class[0]={...db.public_class[0],registration_fee:100,capacity:2,reserved_count:0,revision:0,starts_at:new Date(Date.now()+3600000).toISOString()};db.public_class_enrollment=[];const e=engine(db);
 const run=(accountId,operation,payload={})=>{let output;const backup=structuredClone(db);try{vm.runInNewContext(source,{context:{getArg:k=>k==='wechat_pay_key'?KEY:{operation,payload,actor:{accountId}},setReturn:(k,v)=>{output=v},runGql:(name,q,v,o)=>name==='PaymentBuyer'?{account_by_pk:db.account.find(a=>a.id===v.id)}:e.runGql(name,q,v,o)}});}catch(err){for(const k of Object.keys(db))db[k]=backup[k];throw err;}return JSON.parse(JSON.stringify(output.result.data));};
 return {db,run};}
function start(r){return r.run(201,'PREPARE_COURSE_PAYMENT',{classId:11,name:'支付测试',phone:'13800000000',amount:0.01});}
function proof(order,extra={}){const o={appid:'wx6dafecca8d5fd24e',mch_id:'1666219884',return_code:'SUCCESS',result_code:'SUCCESS',trade_type:'JSAPI',trade_state:'SUCCESS',openid:'openid-test',out_trade_no:order.orderNo,total_fee:'10000',fee_type:'CNY',transaction_id:'420000000000000001',nonce_str:'测试 nonce',...extra};o.sign=signature(o);return o;}
test('server MD5 matches independent crypto for UTF-8 and padding boundaries',()=>{const scope={};vm.runInNewContext(digest+'\n'+read('backend/consultation/course-payment.js'),Object.assign(scope,{op:'NONE'}));for(let i=0;i<130;i++){const s='文'.repeat(i);assert.equal(scope.payMd5(s),crypto.createHash('md5').update(s).digest('hex').toUpperCase());}});
test('amount comes from course, pending creates no enrollment and retries reuse order',()=>{const r=setup(),p=start(r);assert.equal(p.order.amount,100);assert.equal(p.request.total_fee,'10000');assert.equal(p.request.sign,signature(p.request));assert.equal(r.db.public_class_enrollment.length,0);assert.equal(r.db.public_class[0].reserved_count,0);assert.equal(start(r).order.id,p.order.id);assert.equal(r.db.course_registration_order.length,1);assert.throws(()=>r.run(202,'QUERY_COURSE_PAYMENT',{orderId:p.order.id}),/其他用户/);assert.throws(()=>r.run(null,'PREPARE_COURSE_PAYMENT',{classId:11}),/登录/);});
test('问卷金额固定为19.9元且新订单必须来自有效代理二维码',()=>{const r=setup();r.db.service_provider.push({id:3,account_id:203,service_kind:'AGENT',service_status:'ACTIVE',can_reply:false,can_accept_order:false});Object.assign(r.db.public_class[0],{title:'简易方案梳理',product_kind:'QUESTIONNAIRE',registration_fee:19.9});assert.throws(()=>r.run(201,'PREPARE_COURSE_PAYMENT',{classId:11,name:'家长',phone:'13800000000'}),/管理或代理/);const p=r.run(201,'PREPARE_COURSE_PAYMENT',{classId:11,name:'家长',phone:'13800000000',referrerId:203});assert.equal(p.order.amount,19.9);assert.equal(p.request.total_fee,'1990');assert.equal(p.request.body,'知守-简易方案梳理');});
test('signed payment atomically registers exactly once; duplicates never increment seats',()=>{const r=setup(),p=start(r),gateway=proof(p.order);r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway});r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway});assert.equal(r.db.course_registration_order[0].status,'PAID');assert.equal(r.db.course_registration_order[0].amount_paid,100);assert.equal(r.db.public_class_enrollment.length,1);assert.equal(r.db.public_class[0].reserved_count,1);assert.ok(r.run(201,'QUERY_COURSE_PAYMENT',{orderId:p.order.id}).enrollment);assert.throws(()=>r.run(201,'CANCEL_ENROLLMENT',{enrollmentId:r.db.public_class_enrollment[0].id}),/退款/);});
test('付费课程仅在支付成功并报名后绑定推荐人，重复回调不改归属',()=>{const r=setup(),p=r.run(201,'PREPARE_COURSE_PAYMENT',{classId:11,name:'报名人',phone:'13800000000',referrerId:101});assert.equal(r.db.course_referral.length,0);const gateway=proof(p.order);r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway});r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway});assert.equal(r.db.course_referral.length,1);assert.equal(r.db.course_referral[0].referrer_id,101);assert.equal(r.db.course_referral[0].referred_account_id,201);});
test('forged signature, price, buyer, merchant, currency and unpaid status cannot enroll',()=>{for(const extra of [{total_fee:'1'},{openid:'other'},{mch_id:'other'},{appid:'other'},{fee_type:'USD'},{trade_state:'NOTPAY'},{transaction_id:'bad'},{sign:'0'.repeat(32)}]){const r=setup(),p=start(r),v=proof(p.order,extra);if(extra.sign)v.sign=extra.sign;assert.throws(()=>r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway:v}));assert.equal(r.db.course_registration_order[0].status,'PENDING');assert.equal(r.db.public_class_enrollment.length,0);}});
test('valid payment when full is retained for staff review, never reported as enrolled',()=>{const r=setup(),p=start(r);r.db.public_class[0].reserved_count=2;r.run(null,'CONFIRM_COURSE_PAYMENT',{gateway:proof(p.order)});assert.equal(r.db.course_registration_order[0].status,'PAID_REVIEW');assert.equal(r.db.public_class_enrollment.length,0);assert.equal(r.run(201,'QUERY_COURSE_PAYMENT',{orderId:p.order.id}).enrollment,null);});
test('prepay signature is verified and JSAPI signature is correct',()=>{const r=setup(),p=start(r),v={appid:'wx6dafecca8d5fd24e',mch_id:'1666219884',return_code:'SUCCESS',result_code:'SUCCESS',trade_type:'JSAPI',prepay_id:'wx20260921000000123456',nonce_str:'nonce'};v.sign=signature(v);const data=r.run(201,'SIGN_COURSE_PREPAY',{orderId:p.order.id,gateway:v});const fields={...data.payment};delete fields.paySign;assert.equal(data.payment.paySign,signature(fields));assert.equal(r.db.public_class_enrollment.length,0);v.sign='A'.repeat(32);assert.throws(()=>r.run(201,'SIGN_COURSE_PREPAY',{orderId:p.order.id,gateway:v}));});
test('closed order proof must match order and signed CLOSED state',()=>{const r=setup(),p=start(r);assert.throws(()=>r.run(201,'CLOSE_UNPAID_COURSE_ORDER',{orderId:p.order.id,gateway:proof(p.order,{trade_state:'NOTPAY'})}));r.run(201,'CLOSE_UNPAID_COURSE_ORDER',{orderId:p.order.id,gateway:proof(p.order,{trade_state:'CLOSED'})});assert.equal(r.db.course_registration_order[0].status,'CLOSED');assert.equal(r.db.course_registration_order[0].request_key,null);});
test('strict XML supports WeChat CDATA and rejects duplicate tags, entities, and nesting',()=>{assert.equal(relay.parseXml('<xml><return_code><![CDATA[SUCCESS]]></return_code></xml>').return_code,'SUCCESS');assert.equal(relay.parseXml(relay.xml({body:'知守<&"\''})).body,'知守<&"\'');for(const s of ['<!DOCTYPE xml><xml><x>1</x></xml>','<xml><x>1</x><x>2</x></xml>','<xml><x>&unknown;</x></xml>','<xml><x><y>1</y></x></xml>','<xml><__proto__>x</__proto__></xml>'])assert.throws(()=>relay.parseXml(s));});
test('notification acknowledges only committed confirmation and hides errors',async()=>{const {Readable}=require('node:stream');for(const accepted of [true,false]){let response;const req=Readable.from([relay.xml({return_code:'SUCCESS'})]);req.method='POST';const res={setHeader(){},end(x){response=x}};await relay.notify(req,res,async(jwt,op)=>{assert.equal(jwt,null);assert.equal(op,'CONFIRM_COURSE_PAYMENT');if(!accepted)throw new Error('private');return {confirmed:true}});assert.equal(relay.parseXml(response).return_code,accepted?'SUCCESS':'FAIL');assert.ok(!response.includes('private'));}});
test('browser response never receives signed gateway requests',async()=>{const call=async(jwt,op)=>op==='QUERY_COURSE_PAYMENT'?{order:{id:1,status:'PENDING'},request:{sign:'private'}}:{confirmed:true};const result=await relay.status(call,'token',1,async()=>({return_code:'SUCCESS',result_code:'SUCCESS',trade_state:'NOTPAY'}));assert.equal(result.request,undefined);assert.equal(result.order.id,1);});
