const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const presentation=require('../../utils/coursePresentation');
function page(name,call=async()=>({})){let p;const wx={showToast(){},pageScrollTo(){}};vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../../pages',name,name+'.js'),'utf8'),{Page:v=>p=v,require:n=>n.includes('coursePresentation')?presentation:n.includes('consultationService')?{call,error:(p,e)=>p.setData({error:e.message})}:n.endsWith('/auth')?{requireLogin:()=>true}:{},wx,encodeURIComponent});p.data=structuredClone(p.data);p.setData=function(patch){for(const[k,v]of Object.entries(patch)){const parts=k.split('.');let obj=this.data;for(const key of parts.slice(0,-1))obj=obj[key];obj[parts.at(-1)]=v;}};return p;}
const c={id:'1234567890123456',title:'读懂孩子',status:'PUBLISHED',cover:{url:'https://example.invalid/cover'}};
test('列表微信分享使用实际点击场次的完整 ID、名称及封面',()=>{const p=page('course-manage');p.data.classes=[{...c,id:'1',title:'另一堂课'},c];assert.deepEqual(p.onShareAppMessage({target:{dataset:{id:c.id}}}),{title:c.title,path:'/pages/public-class-detail/public-class-detail?id='+c.id,imageUrl:c.cover.url});assert.equal(p.onShareAppMessage().path,'/pages/public-class/public-class');});
test('未加载、草稿和加载失败均不分享无效课程路径',async()=>{for(const value of [null,{...c,status:'DRAFT'}])assert.equal(presentation.classShare(value).path,'/pages/public-class/public-class');const p=page('course-poster',async()=>{throw Error('网络失败');});p.data.classInfo=c;await p.refresh();assert.equal(p.onShareAppMessage().path,'/pages/public-class/public-class');});
test('课程详情直接微信分享，分享页只读取课程，不生成码或复制外链',async()=>{const calls=[];const p=page('course-poster',async op=>{calls.push(op);return {classInfo:c};});await p.refresh();assert.deepEqual(calls,['GET_CLASS']);assert.equal(p.onShareAppMessage().path,presentation.classShare(c).path);const detail=page('public-class-detail');detail.data.classInfo=c;assert.deepEqual(detail.onShareAppMessage(),p.onShareAppMessage());});
test('课程发布前指出缺项，保留输入且不调用保存',async()=>{let calls=0;const p=page('course-edit',async()=>{calls++;});p.data.allowed=true;p.data.loading=false;p.data.form.title='正在准备的公开课';await p.submit('PUBLISHED');assert.match(p.data.error,/开课日期和时间/);assert.equal(p.data.form.title,'正在准备的公开课');assert.equal(calls,0);});
test('进群方式可以留空并正常发布',async()=>{const payloads=[];const p=page('course-edit',async(op,payload)=>{payloads.push({op,payload});return{id:c.id};});p.data.allowed=true;p.data.loading=false;Object.assign(p.data.form,{title:c.title,date:'2099-01-01',time:'14:00',groupGuide:''});p.refresh=async()=>{};await p.submit('PUBLISHED');assert.equal(p.data.publishError,'');assert.equal(payloads.length,1);assert.equal(payloads[0].payload.groupGuide,'');});
test('保存成功后读取失败仍保留课程 ID 和分享，重试不重新创建',async()=>{const payloads=[];const p=page('course-edit',async(op,payload)=>{if(op==='SAVE_CLASS'){payloads.push(payload);return {id:c.id};}throw Error('读取超时');});p.data.allowed=true;p.data.loading=false;Object.assign(p.data.form,{title:c.title,date:'2099-01-01',time:'14:00',groupGuide:'工作人员电话联系进群'});await p.submit('PUBLISHED');assert.equal(p.classId,c.id);assert.match(p.data.error,/课程已保存/);assert.match(p.data.saveNotice,/课程已发布/);assert.equal(p.onShareAppMessage().path,presentation.classShare(c).path);assert.equal(payloads.length,1);assert.equal(p.data.form.title,c.title);});
test('编辑已有课程分享已保存内容，保留历史链接和图片字段',async()=>{const calls=[];const saved={...c,revision:2,signup_url:'https://example.invalid/legacy',share_code:{id:9,url:'https://example.invalid/code'}};const p=page('course-edit',async(op,payload)=>{calls.push({op,payload});return op==='SAVE_CLASS'?{id:c.id}:{classInfo:saved};});p.classId=c.id;await p.refresh();p.input({currentTarget:{dataset:{key:'title'}},detail:{value:'未保存的标题'}});assert.equal(p.onShareAppMessage().title,c.title);await p.submit('DRAFT');const write=calls.find(x=>x.op==='SAVE_CLASS').payload;assert.equal(write.signupUrl,saved.signup_url);assert.equal(write.shareCodeId,9);});
