const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
test('普通用户固定显示公开课和本人方案，代理功能在独立区域由真实身份控制',()=>{
 const w=read('pages/profile/profile.wxml'),j=read('pages/profile/profile.js'),customer=read('pages/customer/customer.wxml');
 const mine=w.slice(w.indexOf('settings-caption">我的服务'),w.indexOf('<view wx:if="{{canInvite}}"'));
 assert.match(mine,/bindtap="goMyPlan"/);assert.match(mine,/bindtap="goPublicClasses"/);
 assert.doesNotMatch(mine,/wx:if|进入客户端|简易方案梳理|推荐客户|扫码进场/);
 assert.match(w,/<view wx:if="\{\{canInvite\}\}" class="settings-section">/);
 assert.doesNotMatch(j,/loadMyPlan|loadReferralAccess|loadCheckinAccess/);
 assert.match(j,/String\(provider.accountId\) === String\(userInfo.id\)/);
 assert.match(j,/provider.serviceKind === 'AGENT'/);
 assert.match(customer,/wx:if="\{\{hasMyPlan\}\}"[^>]*bindtap="openMyPlan"/);
 for(const file of ['pages/questionnaire/questionnaire.wxml','pages/class-enroll/class-enroll.wxml','pages/invite-login/invite-login.wxml'])assert.doesNotMatch(read(file),/推荐人|推荐归属|代理|inviterName/);
});
test('代理页生成可打开保存的二维码且不显示复制链接',()=>{const w=read('pages/questionnaire-share/questionnaire-share.wxml'),j=read('pages/questionnaire-share/questionnaire-share.js');assert.match(w,/canvas-id="questionnaire-code"/);assert.match(w,/打开二维码大图/);assert.match(w,/长按保存到手机/);assert.doesNotMatch(w+j,/复制链接/);assert.match(j,/questionnaire/);assert.match(j,/showReferralPoster/);});
test('问卷在付款后开放完整字段并限制两个问题',()=>{const w=read('pages/questionnaire/questionnaire.wxml'),j=read('pages/questionnaire/questionnaire.js'),u=read('utils/questionnaire.js');for(const value of ['姓名','性别','年龄','年级','孩子经济来源','问题选项','问题描述','日常表现','家长姓名','联系电话'])assert.match(w,new RegExp(value));assert.match(w,/填写前缴费/);assert.match(j,/priceText:'19\.90'/);assert.match(j,/questionnaire\.pay\(\{name,phone\},this\.data\.offer\.price\)/);assert.match(u,/\(cents\/100\)\.toFixed\(2\)/);assert.match(j,/current\.length>=2/);assert.match(j,/questionnaire\.submit/);});
test('管理账号从发放页进入独立问卷工单并按状态处理',()=>{const shareW=read('pages/questionnaire-share/questionnaire-share.wxml'),shareJ=read('pages/questionnaire-share/questionnaire-share.js'),ordersW=read('pages/questionnaire-work-orders/questionnaire-work-orders.wxml'),ordersJ=read('pages/questionnaire-work-orders/questionnaire-work-orders.js'),app=read('app.json');assert.match(shareJ,/STAFF_CHILD_INTAKES/);assert.match(shareW,/问卷工单/);assert.match(shareW,/集中查看家长资料/);assert.match(shareJ,/questionnaire-work-orders/);assert.match(ordersJ,/STAFF_CHILD_INTAKES/);for(const value of ['待处理','处理中','已完成','全部','处理工单'])assert.match(ordersW+ordersJ,new RegExp(value));assert.match(app,/pages\/questionnaire-work-orders\/questionnaire-work-orders/);});
test('工单详情可设置查看时间后发布回复，家长页到点显示最终正文',()=>{const reviewW=read('pages/questionnaire-review/questionnaire-review.wxml'),reviewJ=read('pages/questionnaire-review/questionnaire-review.js'),customerW=read('pages/questionnaire/questionnaire.wxml'),customerJ=read('pages/questionnaire/questionnaire.js');assert.match(reviewJ,/GET_CHILD_INTAKE/);assert.match(reviewJ,/SAVE_CHILD_FEEDBACK/);assert.match(reviewJ,/feedback_revision/);assert.match(reviewJ,/availableAt:this\.releaseAt\(\)/);for(const value of ['孩子经济来源','问题描述','日常表现','家长姓名','联系电话','家长可查看时间','保存草稿','发布回复'])assert.match(reviewW,new RegExp(value));assert.match(reviewW,/mode="date"/);assert.match(reviewW,/mode="time"/);assert.match(customerW,/我的梳理结果/);assert.match(customerW,/feedbackContent/);assert.match(customerJ,/canViewFeedback/);assert.match(customerJ,/feedback_available_at/);});
test('提交成功页使用独立布局且不再叠加同名提示',()=>{const w=read('pages/questionnaire/questionnaire.wxml'),j=read('pages/questionnaire/questionnaire.js'),s=read('pages/questionnaire/questionnaire.wxss');assert.match(w,/class="success-title"/);assert.match(w,/class="success-body"/);assert.match(s,/\.success-title/);assert.doesNotMatch(j,/showToast\(\{title:'问卷已提交'/);});
