const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'../..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const common=read('backend/consultation/common.js'),authorize=common+'\n'+read('backend/consultation/authorize.js'),review=common+'\n'+read('backend/consultation/service-review.js')+'\ncontext.setReturn("state",s);';
function harness(){
 const db={service_provider:[{id:1,account_id:101,service_kind:'STAFF',service_status:'ACTIVE',can_reply:true,can_accept_order:true},{id:2,account_id:102,service_kind:'STAFF',review_role:'DIRECTOR',service_status:'ACTIVE',can_reply:true,can_accept_order:false},{id:3,account_id:103,service_kind:'GUARDIAN',review_role:'GUARDIAN',service_status:'ACTIVE',can_reply:true,can_accept_order:false},{id:4,account_id:104,service_kind:'GUARDIAN',review_role:'GUARDIAN',service_status:'ACTIVE',can_reply:true}],offline_appointment:[{id:31,customer_id:201,provider_id:1,guardian_id:3,director_id:2,status:'COMPLETED',updated_at:'2026-10-09T00:00:00Z',contact_name:'合成家长',child_info:{name:'合成孩子'}}],consultation_feedback:[],service_review_item:[]};let next=1000,state;
 function match(row,w){if(w._and)return w._and.every(c=>match(row,c));if(w._or)return w._or.some(c=>match(row,c));if(w._not)return !match(row,w._not);const [op,data]=Object.entries(w)[0];const operand=Object.values(data)[0],l=row[operand.left_operand.column],r=operand.right_operand.literal;return op==='_eq'?String(l)===String(r):op==='_lt'?Number(l)<Number(r):op==='_gt'?Number(l)>Number(r):false;}
 function runGql(name,q,v){if(name==='ServiceCaseSummaries'){const result={};for(const key of Object.keys(v)){const table=key[0]==='f'||key[0]==='p'?'consultation_feedback':'service_review_item',rows=db[table].filter(r=>match(r,v[key]));result[key]=key[0]==='f'?rows.sort((a,b)=>b.id-a.id).slice(0,1):{aggregate:{count:rows.length}};}return result;}if(name==='ServiceRows'){const table=q.match(/rows: (\w+)\(/)[1],limit=Number(q.match(/limit: (\d+)/)[1]);return {rows:db[table].filter(r=>match(r,v.where)).sort((a,b)=>b.id-a.id).slice(0,limit)};}if(name==='ServiceInsert'){const table=q.match(/insert_(\w+)\(/)[1];if(db[table].some(r=>r.request_key===v.object.request_key))return {saved:{returning:[],affected_rows:0}};const row={...structuredClone(v.object),id:next++,created_at:new Date().toISOString()};db[table].push(row);return {saved:{returning:[{id:row.id}],affected_rows:1}};}if(name==='ServiceUpdate'){const table=q.match(/update_(\w+)\(/)[1],rows=db[table].filter(r=>match(r,v.where));rows.forEach(r=>Object.assign(r,structuredClone(v.object)));return {saved:{returning:rows.map(r=>({id:r.id})),affected_rows:rows.length}};}throw Error(name);}
 function run(account,operation,payload={}){const before=structuredClone(db);try{const context={getArg:k=>({account_id:account,operation,payload,state})[k],setReturn:(_,v)=>state=structuredClone(v),runGql};vm.runInNewContext(authorize,{context});vm.runInNewContext(review,{context});assert.equal(state.result.ok,true);return state.result.data;}catch(e){for(const key of Object.keys(db))db[key]=before[key];throw e;}}
 function feedback(){run(201,'SEND_SERVICE_FEEDBACK',{appointmentId:31,content:'合成执行反馈',requestKey:'one'});return db.consultation_feedback[0];}
 function draft(kind='REPLY'){const f=kind==='REPLY'?feedback():null;return run(103,'SAVE_SERVICE_DRAFT',{appointmentId:31,kind,feedbackId:f&&f.id,content:'待审核的合成回复',summary:'待审核的合成方案',advice:'合成建议'}).item;}
 function advance(account,item,action='APPROVE',extra={}){return run(account,'REVIEW_SERVICE_ITEM',{itemId:item.id,revision:item.revision,action,...extra}).item;}
 return {db,run,draft,advance,feedback};
}
test('家长反馈重试幂等，普通用户、其他监护专员不能读取或修改其他档案',()=>{const h=harness(),f=h.feedback();h.feedback();assert.equal(h.db.consultation_feedback.length,1);for(const actor of [202,104]){assert.throws(()=>h.run(actor,'GET_SERVICE_CASE',{appointmentId:31}),/其他孩子/);assert.throws(()=>h.run(actor,'SAVE_SERVICE_DRAFT',{appointmentId:31,kind:'REPLY',feedbackId:f.id,content:'越权'}),/其他孩子/);}assert.throws(()=>h.run(201,'SAVE_SERVICE_DRAFT',{appointmentId:31,kind:'PLAN',summary:'越权',role:'GENERAL',account_id:101}),/权限/);});
test('监护专员提交、指定总监复核、总管终审，不能跨级或伪造审核权限',()=>{const h=harness();let item=h.draft();assert.throws(()=>h.advance(103,item,'APPROVE'),/阶段/);item=h.advance(103,item,'SUBMIT');assert.equal(item.stage,'DIRECTOR');for(const actor of [101,103])assert.throws(()=>h.advance(actor,item,'APPROVE',{role:'DIRECTOR'}),/总监/);item=h.advance(102,item);assert.equal(item.stage,'GENERAL');assert.throws(()=>h.advance(102,item,'APPROVE',{availableAt:new Date().toISOString()}),/总管/);item=h.advance(101,item,'APPROVE',{availableAt:new Date().toISOString()});assert.equal(item.stage,'APPROVED');assert.equal(h.db.consultation_feedback[0].status,'REPLIED');assert.equal(item.history.length,4);assert.equal(h.run(201,'GET_SERVICE_CASE',{appointmentId:31}).feedback[0].reply.body.content,'待审核的合成回复');});
test('未终审和未到可见时间的正文及操作记录不会返回给家长',()=>{const h=harness();let item=h.draft();const body=()=>h.run(201,'GET_SERVICE_CASE',{appointmentId:31}).feedback[0].reply;assert.equal(body().body,undefined);assert.equal(body().history,undefined);item=h.advance(103,item,'SUBMIT');item=h.advance(102,item);item=h.advance(101,item,'APPROVE',{availableAt:new Date(Date.now()+3600000).toISOString()});assert.equal(body().body,undefined);assert.equal(h.run(103,'GET_SERVICE_CASE',{appointmentId:31}).feedback[0].reply.body.content,'待审核的合成回复');});
test('旧审核版本不能覆盖新版本，已终审的回复不能编辑',()=>{const h=harness(),original=h.draft();const submitted=h.advance(103,original,'SUBMIT');assert.throws(()=>h.advance(102,original),/已更新/);let item=h.advance(102,submitted);item=h.advance(101,item,'APPROVE',{availableAt:new Date().toISOString()});assert.throws(()=>h.run(103,'SAVE_SERVICE_DRAFT',{appointmentId:31,feedbackId:h.db.consultation_feedback[0].id,kind:'REPLY',revision:item.revision,content:'覆盖'}),/已审核/);});
test('方案要求补充时只公开补充说明，家长补充后回到草稿且保留原方案',()=>{const h=harness();let item=h.draft('PLAN');item=h.advance(103,item,'SUBMIT');assert.throws(()=>h.advance(102,item,'SUPPLEMENT'),/说明/);item=h.advance(102,item,'SUPPLEMENT',{note:'请补充每天作息'});const parent=h.run(201,'GET_SERVICE_CASE',{appointmentId:31}).plan;assert.equal(parent.body,undefined);assert.equal(parent.supplementNote,'请补充每天作息');h.run(201,'SUPPLEMENT_SERVICE_CASE',{appointmentId:31,itemId:item.id,revision:item.revision,content:'合成作息补充'});const plan=h.run(103,'GET_SERVICE_CASE',{appointmentId:31}).plan;assert.equal(plan.stage,'DRAFT');assert.equal(plan.body.summary,'待审核的合成方案');assert.equal(plan.body.parentSupplement,'合成作息补充');});
test('只允许总管分配人员，失效总监或空总监不能提交审核',()=>{const h=harness();assert.throws(()=>h.run(103,'ASSIGN_SERVICE_CASE',{appointmentId:31}),/总管/);assert.throws(()=>h.run(201,'LIST_SERVICE_STAFF'),/总管/);let item=h.draft();h.db.offline_appointment[0].director_id=null;assert.throws(()=>h.advance(103,item,'SUBMIT'),/分配总监/);h.db.offline_appointment[0].director_id=2;h.db.service_provider[1].service_status='INACTIVE';assert.throws(()=>h.advance(103,item,'SUBMIT'),/复核权限/);});
test('本人的档案列表不返回别人档案，草稿内容不进待办列表',()=>{const h=harness();h.db.offline_appointment.push({id:32,customer_id:202,status:'COMPLETED',provider_id:1,child_info:{name:'其他孩子'}});h.draft();const own=h.run(201,'SERVICE_CHAT_OVERVIEW');assert.deepEqual(Array.from(own.cases,c=>c.id),[31]);assert.doesNotMatch(JSON.stringify(own),/待审核的合成回复/);assert.equal(h.run(103,'SERVICE_CHAT_OVERVIEW').cases.length,1);});
