const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
function loginHarness(){const navigations=[],toasts=[];const scope={module:{exports:{}},wx:{navigateTo:arg=>navigations.push(arg),showToast:arg=>toasts.push(arg)}};vm.runInNewContext(fs.readFileSync(path.join(root,'utils/loginReturn.js'),'utf8'),scope);return {api:scope.module.exports,navigations,toasts};}
test('报名登录后回到同一场次，姓名手机仅在当前会话中恢复一次',()=>{const h=loginHarness();h.api.remember({route:'pages/class-enroll/class-enroll',options:{id:'12'}},{enrollmentForm:{name:'家长甲',phone:'13800000000',accountId:'forged'}});assert.equal(h.api.resume(),true);assert.equal(h.navigations[0].url,'/pages/class-enroll/class-enroll?id=12');assert.deepEqual(JSON.parse(JSON.stringify(h.api.takeEnrollmentForm('12'))),{name:'家长甲',phone:'13800000000'});assert.equal(h.api.takeEnrollmentForm('12'),null);assert.equal(h.api.resume(),false);});
test('登录恢复不能跳转任意地址，不能跨场次带入个人信息',()=>{const h=loginHarness();for(const page of [{route:'https://example.com'},{route:'pages/class-enroll/class-enroll',options:{id:'12&role=admin'}},{route:'pages/profile/profile'}]){h.api.remember(page);assert.equal(h.api.resume(),false);}h.api.remember({route:'pages/class-enroll/class-enroll',options:{id:12}},{enrollmentForm:{name:'家长'}});h.api.resume();assert.equal(h.api.takeEnrollmentForm('13'),null);});
test('主动退出登录清理未完成的返回意图',()=>{const h=loginHarness();h.api.remember({route:'pages/class-ticket/class-ticket',options:{id:21}});h.api.clear();assert.equal(h.api.resume(),false);});
test('只有家长确认去登录才保存返回场次，取消弹窗不跳转',()=>{const remembered=[],nav=[];let dialog;const scope={module:{exports:{}},getCurrentPages:()=>[{route:'pages/class-enroll/class-enroll',options:{id:11}}],require:()=>({remember:(...args)=>remembered.push(args),clear:()=>{}}),wx:{getStorageSync:()=>null,showModal:d=>dialog=d,switchTab:d=>nav.push(d)}};vm.runInNewContext(fs.readFileSync(path.join(root,'utils/auth.js'),'utf8'),scope);const auth=scope.module.exports;assert.equal(auth.requireLogin('登录继续',{enrollmentForm:{name:'家长'}}),false);dialog.success({confirm:false});assert.equal(remembered.length,0);auth.requireLogin('登录继续',{enrollmentForm:{name:'家长'}});dialog.success({confirm:true});assert.equal(remembered[0][0].options.id,11);assert.equal(remembered[0][1].enrollmentForm.name,'家长');assert.equal(nav[0].url,'/pages/profile/profile');});
function consultationHarness(){let page;const response={appointment:{id:31,status:'CONFIRMED',contact_name:'家长',child_info:{name:'已保存的孩子',age:8}},record:{summary:'已保存的老师记录',advice:[]},feedbacks:[],summaryJobs:[],isStaff:true,canReply:true,canAccept:true};const service={requestKey:()=> 'request',decorate:x=>x,call:async()=>structuredClone(response),error:(p,e)=>p.setData({error:e.message})};vm.runInNewContext(fs.readFileSync(path.join(root,'pages/consultation-detail/consultation-detail.js'),'utf8'),{Page:p=>page=p,require:name=>name.includes('consultationService')?service:{requireLogin:()=>true,restore:()=>false},wx:{showToast:()=>{},showModal:o=>o.success({confirm:true})},clearInterval,Date,setInterval});page.data=structuredClone(page.data);page.setData=function(values){for(const [key,value] of Object.entries(values)){const parts=key.split('.');let target=this.data;for(const part of parts.slice(0,-1))target=target[part];target[parts.at(-1)]=value;}};page.onLoad({id:31});return {page,response,service};}
test('咨询页刷新反馈不会覆盖未保存的孩子信息和老师记录',async()=>{const {page}=consultationHarness();await page.refresh();page.inputChild({currentTarget:{dataset:{key:'name'}},detail:{value:'正在填写的孩子'}});page.inputRecord({currentTarget:{dataset:{key:'summary'}},detail:{value:'尚未保存的沟通记录'}});await page.refresh();assert.equal(page.data.childForm.name,'正在填写的孩子');assert.equal(page.data.recordForm.summary,'尚未保存的沟通记录');});
test('采用AI草稿后刷新任务状态仍保留待检查的正文',async()=>{const {page}=consultationHarness();await page.refresh();page.setData({summaryJobs:[{id:71,draft:'AI草稿，待老师检查'}]});page.useSummary({currentTarget:{dataset:{id:71}}});await page.refresh();assert.equal(page.data.recordForm.summary,'AI草稿，待老师检查');});
test('保存成功才允许后端回读替换表单，保存失败保留编辑',async()=>{const {page,response,service}=consultationHarness();await page.refresh();page.inputRecord({currentTarget:{dataset:{key:'summary'}},detail:{value:'新内容'}});service.call=async op=>{if(op==='SAVE_RECORD')throw new Error('保存失败');return structuredClone(response);};assert.equal(await page.run('SAVE_RECORD',{}),false);assert.equal(page.dirtyRecord,true);assert.equal(page.data.recordForm.summary,'新内容');service.call=async op=>{if(op==='SAVE_RECORD'){response.record.summary='新内容';return {id:41};}return structuredClone(response);};assert.equal(await page.run('SAVE_RECORD',{}),true);assert.equal(page.dirtyRecord,false);assert.equal(page.data.recordForm.summary,'新内容');});
test('保存等待期间继续输入的内容不会被旧保存结果覆盖',async()=>{const {page,response,service}=consultationHarness();await page.refresh();page.inputRecord({currentTarget:{dataset:{key:'summary'}},detail:{value:'第一版'}});let saved;service.call=op=>op==='SAVE_RECORD'?new Promise(resolve=>saved=resolve):Promise.resolve(structuredClone(response));const request=page.run('SAVE_RECORD',{summary:'第一版'});assert.equal(page.data.busy,true);page.inputRecord({currentTarget:{dataset:{key:'summary'}},detail:{value:'第一版之后的补充'}});response.record.summary='第一版';saved({id:41});await request;assert.equal(page.data.recordForm.summary,'第一版之后的补充');assert.equal(page.dirtyRecord,true);assert.equal(page.data.busy,false);});
