const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
const tick=()=>new Promise(r=>setImmediate(r));
function harness(name,overrides={}){
 const storage={userInfo:{id:'101',nickName:'本人'},zionJwt:'token-A',consultationSessionId:'A',currentChatRole:'manager'},toasts=[],nav=[];let p;
 const wx={getStorageSync:k=>storage[k],setStorageSync:(k,v)=>storage[k]=v,removeStorageSync:k=>delete storage[k],showToast:o=>toasts.push(o.title),showModal:o=>o.success?.({confirm:true}),navigateTo:o=>nav.push(o.url),navigateBack(){},switchTab:o=>nav.push(o.url),setNavigationBarTitle(){},pageScrollTo(){},setClipboardData:o=>wx.copied=o.data};
 const modules={zion:{},consultationService:{call:async()=>({}),requestKey:()=> 'key',decorate:x=>x,error:(p,e)=>p.setData({error:e.message})},...overrides};
 const cache={};function load(file){const key=path.basename(file,'.js');if(modules[key])return modules[key];if(cache[file])return cache[file].exports;const mod={exports:{}};cache[file]=mod;vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:mod,require:n=>n.startsWith('.')?load(path.resolve(path.dirname(file),n+'.js')):require(n),wx,getCurrentPages:()=>p?[p]:[],Page:v=>p=v,setInterval:()=>1,clearInterval(){},setTimeout:f=>f(),Date,console:{warn(){}}},{filename:file});return mod.exports;}
 load(path.join(root,'pages',name,name+'.js'));p.data=structuredClone(p.data);p.route=`pages/${name}/${name}`;p.options={};p.setData=function(values,callback){for(const[k,v]of Object.entries(values)){const parts=k.split('.');let obj=this.data;for(const part of parts.slice(0,-1))obj=obj[part]||(obj[part]={});obj[parts.at(-1)]=v;}callback?.();};
 return {p,wx,storage,toasts,nav,load};
}
test('聊天慢校验期间连点只提交一次，后续输入不被清空',async()=>{const d=deferred(),sent=[];const h=harness('chat',{zion:{sendManagerReply:async x=>sent.push(x)}});h.p.setData({input:'第一条',chatRole:'manager'});h.p.syncSessionAccessFromBackend=()=>d.promise;h.p.loadBackendMessages=async()=>{};const a=h.p.sendMessage();const b=h.p.sendMessage();h.p.setData({input:'新的草稿'});d.resolve(true);await Promise.all([a,b]);assert.equal(sent.length,1);assert.equal(sent[0].sessionId,'A');assert.equal(h.p.data.input,'新的草稿');assert.equal(h.p.data.sending,false);});
test('切换账号/会话或离页后，未完成的发送校验不能继续发消息',async()=>{for(const change of ['account','session','hide']){const d=deferred(),sent=[];const h=harness('chat',{zion:{sendManagerReply:async x=>sent.push(x)}});h.p.setData({input:'A的内容',chatRole:'manager'});h.p.syncSessionAccessFromBackend=()=>d.promise;const task=h.p.sendMessage();if(change==='account')h.storage.zionJwt='token-B';if(change==='session')h.storage.consultationSessionId='B';if(change==='hide'){h.p.hidden=true;h.p.viewEpoch=1;}d.resolve(true);await task;assert.equal(sent.length,0);}});
test('聊天失败保留可复制原文，并允许重试',async()=>{let failed=true,writes=0;const h=harness('chat',{zion:{sendManagerReply:async()=>{writes++;if(failed)throw Error('offline');}}});h.p.setData({input:'重要正文',chatRole:'manager'});h.p.syncSessionAccessFromBackend=async()=>true;h.p.loadBackendMessages=async()=>{};await h.p.sendMessage();assert.equal(h.p.data.input,'重要正文');assert.match(h.p.data.sendError,/原文已保留/);h.p.copyUnsentMessage();assert.equal(h.wx.copied,'重要正文');failed=false;await h.p.sendMessage();assert.equal(h.p.data.input,'');assert.equal(writes,2);});
test('A消息迟到不能覆盖B；B请求不必等待A完成',async()=>{const a=deferred(),b=deferred();const h=harness('chat',{zion:{getSessionMessages:id=>id==='A'?a.promise:b.promise}});h.p.toDisplayMessage=x=>x;h.p.setData({isManagerView:false});h.storage.currentChatRole='customer';const first=h.p.loadBackendMessages();h.storage.consultationSessionId='B';const second=h.p.loadBackendMessages();b.resolve({messages:[{id:'b',content:'客户B'}]});await second;a.resolve({messages:[{id:'a',content:'客户A'}]});await first;assert.equal(h.p.data.messages[0].content,'客户B');});
test('旧会话的计时回填不能污染新会话缓存',async()=>{const d=deferred();const h=harness('chat',{zion:{getConsultationSession:()=>d.promise}});const job=h.p.hydrateSessionTiming(true);h.storage.consultationSessionId='B';h.storage.currentSessionStatus='active';d.resolve({id:'A',status:'closed'});assert.equal(await job,false);assert.equal(h.storage.currentSessionStatus,'active');});
test('资料忽略其他账号的历史草稿，慢响应保护编辑字段',async()=>{const d=deferred();const h=harness('profile-edit',{zion:{getAccountProfile:()=>d.promise}});h.storage.profileDraft={userName:'其他账号',detailAddress:'不应出现'};const job=h.p.loadProfile();assert.equal(h.p.data.userName,'本人');assert.equal(h.p.data.detailAddress,'');h.p.onUserNameInput({detail:{value:'新的名字'}});d.resolve({id:'101',nickName:'数据库旧名',region:'上海'});await job;assert.equal(h.p.data.userName,'新的名字');assert.equal(h.p.data.region,'上海');assert.equal(h.storage.profileDraft,undefined);});
test('资料旧账号回填和保存结果不得写入换号后的缓存',async()=>{const d=deferred();const h=harness('profile-edit',{zion:{getAccountProfile:()=>d.promise}});const job=h.p.loadProfile();h.storage.userInfo={id:'202',nickName:'新账号'};h.storage.zionJwt='token-B';d.resolve({id:'101',nickName:'旧账号'});await job;assert.equal(h.storage.userInfo.id,'202');});
test('资料查重展示字段错误，不错误上传头像或写入',async()=>{let uploads=0;const h=harness('profile-edit',{zion:{isUsernameAvailable:async()=>false,uploadImage:async()=>uploads++}});h.p.identity=h.load(path.join(root,'utils/viewSession.js')).capture();h.p.setData({userName:'重名',avatarUrl:'wxfile://avatar'});await h.p.saveProfile();assert.match(h.p.data.usernameError,/已被使用/);assert.equal(uploads,0);assert.equal(h.p.data.saving,false);});
test('资料保存阻止连点，正常持久化返回值作为界面来源',async()=>{const d=deferred();let writes=0;const h=harness('profile-edit',{zion:{isUsernameAvailable:()=>d.promise,saveAccountProfile:async p=>{writes++;return {id:'101',nickName:p.userName,region:'已确认城市'};}}});h.p.identity=h.load(path.join(root,'utils/viewSession.js')).capture();h.p.setData({userName:'新名'});const one=h.p.saveProfile();const two=h.p.saveProfile();d.resolve(true);await Promise.all([one,two]);assert.equal(writes,1);assert.equal(h.storage.userInfo.region,'已确认城市');});
test('留言、反馈及回复仅清空发送的版本',async()=>{for(const kind of ['note','feedback','reply']){const d=deferred();const h=harness('consultation-detail');h.p.onLoad({id:'31'});h.p.run=()=>d.promise;const data=kind==='note'?{noteContent:'旧正文'}:kind==='feedback'?{feedbackContent:'旧正文',record:{advice:[{key:'step-1'}]}}:{replyContents:{51:'旧正文'}};h.p.setData(data);const job=kind==='note'?h.p.sendNote():kind==='feedback'?h.p.sendFeedback():h.p.sendReply({currentTarget:{dataset:{id:51}}});if(kind==='note')h.p.inputNote({detail:{value:'新正文'}});else if(kind==='feedback')h.p.inputFeedback({detail:{value:'新正文'}});else h.p.inputReply({detail:{value:'新正文'},currentTarget:{dataset:{id:51}}});d.resolve(true);await job;assert.equal(kind==='note'?h.p.data.noteContent:kind==='feedback'?h.p.data.feedbackContent:h.p.data.replyContents[51],'新正文');}});
test('课程保存回读保留保存期间的新修改和新的版本号',async()=>{const d=deferred();const h=harness('course-edit',{consultationService:{call:op=>op==='SAVE_CLASS'?d.promise:Promise.resolve({classInfo:{id:1,title:'旧提交',status:'DRAFT',revision:2}}),error:(p,e)=>p.setData({error:e.message})}});h.p.classId=1;h.p.setData({allowed:true,loading:false,'form.title':'旧提交'});const job=h.p.submit('DRAFT');h.p.input({currentTarget:{dataset:{key:'title'}},detail:{value:'新增修改'}});d.resolve({id:1});await job;assert.equal(h.p.data.form.title,'新增修改');assert.equal(h.p.revision,2);assert.match(h.p.data.saveNotice,/仍待保存/);});
test('三个分页搜索页面更换关键词时必须丢弃旧游标和旧结果',async()=>{for(const name of ['public-class','course-manage','course-roster']){const calls=[];const h=harness(name,{consultationService:{call:async(op,p)=>{calls.push(p);return {classes:[{id:2}],items:[{id:2,public_class:{}}],classInfo:{},stats:{}}},decorate:x=>x,formatTime:()=>"",error(p,e){throw e;}}});h.p.setData({loading:false,search:'成都',classes:[{id:1}],items:[{id:1}],nextCursor:99});h.p.appliedSearch='北京';await h.p.load(true);assert.equal(calls[0].cursor,null);assert.equal((name==='course-roster'?h.p.data.items:h.p.data.classes).length,1);}});
test('加载期间确认的新搜索在上一请求后自动执行',async()=>{const d=deferred(),calls=[];const h=harness('public-class',{consultationService:{call:async(op,p)=>{calls.push(p);if(calls.length===1)return d.promise;return {classes:[{id:2}],nextCursor:null};},decorate:x=>x,formatTime:()=>"",error(p,e){throw e;}}});const task=h.p.refresh();h.p.searchInput({detail:{value:'最新条件'}});h.p.refresh();d.resolve({classes:[{id:1}],nextCursor:99});await task;await tick();assert.equal(calls.length,2);assert.equal(calls[1].search,'最新条件');});
test('课程搜索实际命中课程，并导航到该课程详情',async()=>{const h=harness('search',{zion:{listCourses:async()=>({courses:[{id:11,title:'亲密关系沟通基础课'}]})}});h.p.setData({mode:'courses'});await h.p.refresh();h.p.onKeywordInput({detail:{value:'亲密关系'}});assert.equal(h.p.data.results[0].id,11);assert.equal(h.p.data.results[0].detailUrl,'/pages/course-detail/course-detail?id=11');});
test('不存在的课程保持空数据并解释原因，不再显示其他示例课程',async()=>{const h=harness('course-detail',{zion:{getCourse:async()=>({course:null})}});await h.p.fetchCourse('999');assert.equal(h.p.data.course,null);assert.match(h.p.data.error,/不存在/);});
test('认证失效清空登录态，旧token失败不会登出新账号',()=>{const h=harness('profile');h.p.route='pages/profile/profile';const auth=h.load(path.join(root,'utils/auth.js'));h.storage.zionJwt='new';auth.expire('old');assert.equal(h.storage.zionJwt,'new');auth.expire('new');assert.equal(h.storage.zionJwt,undefined);assert.equal(h.p.data.isLoggedIn,false);assert.equal(h.nav[0],'/pages/profile/profile');});
test('登录恢复表单仅交还原账号，不跨账号恢复',()=>{for(const nextAccount of ['101','202']){const h=harness('customer');h.p.setData({showForm:true,'form.concerns':'私有草稿'});const api=h.load(path.join(root,'utils/loginReturn.js'));api.remember(h.p,{accountId:'101',preserveForm:true});h.storage.userInfo={id:nextAccount};api.resume();h.p.setData({'form.concerns':''});const restored=api.restore(h.p,'customer','');assert.equal(restored,nextAccount==='101');assert.equal(h.p.data.form.concerns,nextAccount==='101'?'私有草稿':'');}});
test('手工刷新课程不覆盖未保存草稿，保存回读期间的新编辑继续保留',async()=>{
 const read=deferred();let delay=false;const h=harness('course-edit',{consultationService:{call:async op=>op==='SAVE_CLASS'?{id:1}:delay?read.promise:{classInfo:{id:1,title:'数据库正文',status:'DRAFT',revision:2}},error:(p,e)=>p.setData({error:e.message})}});
 h.p.classId=1;await h.p.refresh();h.p.input({currentTarget:{dataset:{key:'title'}},detail:{value:'待保存正文'}});await h.p.refresh();assert.equal(h.p.data.form.title,'待保存正文');
 delay=true;const saving=h.p.submit('DRAFT');await tick();h.p.input({currentTarget:{dataset:{key:'title'}},detail:{value:'回读中的新正文'}});read.resolve({classInfo:{id:1,title:'待保存正文',status:'DRAFT',revision:3}});await saving;assert.equal(h.p.data.form.title,'回读中的新正文');assert.match(h.p.data.saveNotice,/仍待保存/);
});
test('加载更多迟到时不能追加到刷新的预约或反馈列表',async()=>{for(const name of ['customer','service-workbench','consultation-detail']){
 const old=deferred();let calls=0;const data={appointments:[{id:9}],appointment:{id:31},feedbacks:[{id:9}],summaryJobs:[],nextAppointmentCursor:null,nextFeedbackCursor:null};
 const h=harness(name,{consultationService:{call:async()=>++calls===1?old.promise:data,decorate:x=>x,error:(p,e)=>p.setData({error:e.message})}});
 h.p.setData({loading:false,appointments:[{id:1}],feedbacks:[{id:1}],nextAppointmentCursor:10,nextFeedbackCursor:10});
 const more=name==='consultation-detail'?h.p.moreHistory({currentTarget:{dataset:{kind:'feedback'}}}):h.p.moreAppointments();await h.p.refresh();old.resolve({appointments:[{id:2}],feedbacks:[{id:2}],nextAppointmentCursor:2,nextFeedbackCursor:2});await more;
 assert.deepEqual((name==='consultation-detail'?h.p.data.feedbacks:h.p.data.appointments).map(x=>x.id),[9]);assert.equal(h.p.data.moreLoading,false);
}});
test('经理身份慢响应不应把旧账号权限写回新账号',async()=>{const d=deferred();const h=harness('chat',{zion:{getServiceProviderByAccount:()=>d.promise}});h.storage.currentChatRole='customer';const loading=h.p.detectManagerDrawerAccess();h.storage.userInfo={id:'202'};h.storage.zionJwt='token-B';d.resolve({id:1,accountId:'101',serviceStatus:'ACTIVE'});assert.equal(await loading,false);assert.equal(h.storage.activeServiceProviderId,undefined);});
test('聊天登录恢复正文同时绑定账号和原会话',()=>{for(const session of ['A','B']){const h=harness('chat');h.p.setData({input:'原会话草稿'});const api=h.load(path.join(root,'utils/loginReturn.js'));api.remember(h.p,{accountId:'101',preserveForm:true});api.resume();h.storage.consultationSessionId=session;h.p.setData({input:''});const restored=api.restore(h.p,'chat','');assert.equal(restored,session==='A');assert.equal(h.p.data.input,session==='A'?'原会话草稿':'');}});
