const service=require('./consultationService');
const auth=require('./auth');
const viewSession=require('./viewSession');
const archive=require('./childArchive');
const stages={DRAFT:'监护专员整理',DIRECTOR:'总监复核',GENERAL:'总管终审',APPROVED:'已审核',SUPPLEMENT:'待家长补充'};
const roles={GENERAL:'总管',DIRECTOR:'总监',GUARDIAN:'监护专员'};
const actions={CREATE:'创建草稿',SAVE_DRAFT:'保存草稿',SUBMIT:'提交复核',APPROVE:'审核通过',RETURN:'退回修改',SUPPLEMENT:'要求补充信息',PARENT_SUPPLEMENT:'家长补充信息'};
function decorate(item){return item?{...item,stageText:stages[item.stage]||item.stage,availableText:item.availableAt?service.formatTime(item.availableAt):'',history:(item.history||[]).map(h=>({...h,roleText:roles[h.role]||(h.action==='PARENT_SUPPLEMENT'?'家长':'工作人员'),actionText:actions[h.action]||h.action,timeText:service.formatTime(h.at)}))}:null;}
const data={serviceMode:false,serviceLoading:true,serviceBusy:false,serviceError:'',serviceRole:'',serviceRoleLabel:'家长',serviceStaff:false,serviceCanManage:false,serviceCases:[],serviceAllCases:[],serviceCaseCursor:null,serviceDrawer:false,serviceSearch:'',serviceFilter:'ALL',serviceSortNewest:true,serviceActive:null,serviceDetail:null,serviceFeedback:[],serviceFeedbackCursor:null,servicePlan:null,serviceTab:'feedback',serviceInput:'',serviceDraftId:'',serviceDraftRevision:null,serviceDraftFeedbackId:'',serviceDraftKind:'REPLY',servicePlanSummary:'',servicePlanAdvice:'',servicePlanEditing:false,serviceNote:'',serviceReleaseHours:'6',serviceStaffOptions:[],serviceGuardianIndex:0,serviceDirectorIndex:0,serviceAssignOpen:false,serviceMeta:{level:'',subLevel:'',danger:'',memo:'',phase:'',priority:false},serviceLevelOptions:['','A','B','C','D'],serviceLevels:['全部','A','B','C','D'],serviceLevelFilter:0};
function current(page,identity,epoch){return !page.hidden&&!page.unloaded&&viewSession.current(identity)&&page.serviceEpoch===epoch;}
const methods={
 stopServiceChat(){clearInterval(this.servicePoll);this.servicePoll=null;this.serviceEpoch=(this.serviceEpoch||0)+1;this.serviceCaseRequest=null;},
 async loadServiceChat(){
  if(!auth.isLoggedIn())return;this.stopServiceChat();const identity=viewSession.capture(),epoch=this.serviceEpoch;if(this.serviceChatIdentity&&!viewSession.current(this.serviceChatIdentity)){this.serviceSelectedId=null;this.servicePending=null;}this.serviceChatIdentity=identity;
  this.setData({serviceMode:true,serviceLoading:true,serviceError:'',serviceCases:[],serviceAllCases:[],serviceActive:null,serviceMeta:{},serviceRole:'',serviceRoleLabel:'家长',serviceDetail:null,serviceFeedback:[],servicePlan:null,serviceInput:'',serviceStaff:false,serviceCanManage:false,serviceDrawer:false});
  try{const r=await service.call('SERVICE_CHAT_OVERVIEW');if(!current(this,identity,epoch))return;this.setData({serviceMode:!!r.staff||(r.cases||[]).length>0,serviceAllCases:r.cases||[],serviceCaseCursor:r.nextCursor||null,serviceStaff:r.staff,serviceCanManage:r.canManage,serviceRole:r.role,serviceRoleLabel:roles[r.role]||'家长'});this.filterServiceCases();const first=this.data.serviceCases.find(c=>String(c.id)===String(this.serviceSelectedId))||this.data.serviceCases[0];if(first)await this.selectServiceCase({currentTarget:{dataset:{id:first.id}}});}
  catch(e){if(current(this,identity,epoch))this.setData({serviceError:e.message});}
  finally{if(current(this,identity,epoch)){this.setData({serviceLoading:false});this.servicePoll=setInterval(()=>{if(!this.data.serviceBusy&&!this.data.serviceDrawer&&this.serviceSelectedId)this.refreshServiceCase(true);},8000);}}
 },
 async moreServiceCases(){if(!this.data.serviceCaseCursor||this.data.serviceBusy)return;const identity=this.serviceChatIdentity,epoch=this.serviceEpoch;this.setData({serviceBusy:true});try{const r=await service.call('SERVICE_CHAT_OVERVIEW',{cursor:this.data.serviceCaseCursor});if(!current(this,identity,epoch))return;this.setData({serviceAllCases:this.data.serviceAllCases.concat(r.cases||[]),serviceCaseCursor:r.nextCursor||null});this.filterServiceCases();}catch(e){if(current(this,identity,epoch))this.setData({serviceError:e.message});}finally{if(current(this,identity,epoch))this.setData({serviceBusy:false});}},
 filterServiceCases(){const q=this.data.serviceSearch.trim().toLowerCase(),filter=this.data.serviceFilter,level=this.data.serviceLevelFilter;let cases=this.data.serviceAllCases.filter(c=>(!q||[c.childName,c.parentName,c.id,c.latest].join(' ').toLowerCase().includes(q))&&(!level||c.metadata&&c.metadata.level===this.data.serviceLevels[level])&&(filter==='ALL'||filter==='PRIORITY'&&c.metadata&&c.metadata.priority||filter==='PENDING'&&c.pending>0||filter==='DIRECTOR'&&(c.reviewStages||[]).includes('DIRECTOR')||filter==='GENERAL'&&(c.reviewStages||[]).includes('GENERAL')));cases.sort((a,b)=>this.data.serviceSortNewest?Number(b.id)-Number(a.id):Number(a.id)-Number(b.id));this.setData({serviceCases:cases});},
 searchServiceCases(e){this.setData({serviceSearch:e.detail.value});this.filterServiceCases();},
 changeServiceFilter(e){this.setData({serviceFilter:e.currentTarget.dataset.filter});this.filterServiceCases();},
 changeServiceLevel(e){this.setData({serviceLevelFilter:Number(e.detail.value)});this.filterServiceCases();},
 sortServiceCases(){this.setData({serviceSortNewest:!this.data.serviceSortNewest});this.filterServiceCases();},
 toggleServiceDrawer(){this.setData({serviceDrawer:!this.data.serviceDrawer});},
 closeServiceDrawer(){this.setData({serviceDrawer:false});},
 async selectServiceCase(e){if(this.data.serviceBusy)return;const id=e.currentTarget.dataset.id;if(this.serviceSelectedId&&String(id)!==String(this.serviceSelectedId)&&this.data.serviceInput){wx.showModal({title:'切换孩子档案',content:'当前有未提交内容，切换后将清空输入。',success:r=>{if(r.confirm){this.setData({serviceInput:''});this.selectServiceCase(e);}}});return;}this.serviceSelectedId=id;this.serviceCaseVersion=(this.serviceCaseVersion||0)+1;this.serviceCaseRequest=null;this.setData({serviceActive:this.data.serviceAllCases.find(c=>String(c.id)===String(id)),serviceDrawer:false,serviceDetail:null,serviceFeedback:[],servicePlan:null,serviceInput:'',servicePlanSummary:'',servicePlanAdvice:'',serviceDraftId:'',serviceDraftRevision:null,serviceDraftFeedbackId:'',serviceAssignOpen:false,servicePlanEditing:false,serviceTab:'feedback'});await this.refreshServiceCase();},
 async refreshServiceCase(silent=false,more=false){if(!this.serviceSelectedId||this.serviceCaseRequest)return;const identity=this.serviceChatIdentity,epoch=this.serviceEpoch,id=this.serviceSelectedId,version=this.serviceCaseVersion,request={};this.serviceCaseRequest=request;if(!silent)this.setData({serviceLoading:true,serviceError:''});try{const r=await service.call('GET_SERVICE_CASE',{appointmentId:id,...(more?{beforeId:this.data.serviceFeedbackCursor}:{})});if(!current(this,identity,epoch)||version!==this.serviceCaseVersion)return;const feedback=(r.feedback||[]).map(f=>({...f,timeText:service.formatTime(f.createdAt),reply:decorate(f.reply)}));const existing=more?this.data.serviceFeedback:[];this.setData({serviceDetail:r,serviceFeedback:existing.concat(feedback),serviceFeedbackCursor:r.nextCursor||null,servicePlan:decorate(r.plan),...(!this.data.serviceAssignOpen?{serviceMeta:r.appointment.service_metadata||{}}:{}),serviceArchiveSections:archive.answeredSections(r.appointment.child_info||{}),serviceError:''});}catch(e){if(current(this,identity,epoch)&&version===this.serviceCaseVersion)this.setData({serviceError:e.message});}finally{if(this.serviceCaseRequest===request){this.serviceCaseRequest=null;if(current(this,identity,epoch))this.setData({serviceLoading:false});}}},
 moreServiceFeedback(){return this.refreshServiceCase(false,true);},
 switchServiceTab(e){this.setData({serviceTab:e.currentTarget.dataset.tab,serviceAssignOpen:false,serviceDraftFeedbackId:'',servicePlanEditing:false});},
 inputService(e){this.setData({[e.currentTarget.dataset.field||'serviceInput']:e.detail.value});},
 selectServiceReply(e){const f=this.data.serviceFeedback.find(f=>String(f.id)===String(e.currentTarget.dataset.id));if(!f)return;const r=f.reply;this.setData({serviceDraftFeedbackId:f.id,serviceDraftKind:'REPLY',serviceDraftId:r&&r.id||'',serviceDraftRevision:r?r.revision:null,serviceInput:r&&r.body&&r.body.content||'',serviceNote:''});},
 async serviceAction(operation,payload){if(this.data.serviceBusy)return false;const identity=this.serviceChatIdentity,epoch=this.serviceEpoch,version=this.serviceCaseVersion;this.setData({serviceBusy:true,serviceError:''});try{const r=await service.call(operation,payload);if(!current(this,identity,epoch)||version!==this.serviceCaseVersion)return false;return r;}catch(e){if(current(this,identity,epoch)&&version===this.serviceCaseVersion)this.setData({serviceError:e.message});return false;}finally{if(current(this,identity,epoch)&&version===this.serviceCaseVersion)this.setData({serviceBusy:false});}},
 async sendServiceFeedback(){const content=this.data.serviceInput.trim();if(!content)return;const version=this.serviceCaseVersion;if(!this.servicePending||this.servicePending.content!==content)this.servicePending={content,key:service.requestKey()};const r=await this.serviceAction('SEND_SERVICE_FEEDBACK',{appointmentId:this.serviceSelectedId,content,requestKey:this.servicePending.key});if(r&&version===this.serviceCaseVersion){this.servicePending=null;if(this.data.serviceInput.trim()===content)this.setData({serviceInput:''});await this.refreshServiceCase();}},
 editServicePlan(){const plan=this.data.servicePlan;this.setData({servicePlanEditing:true,serviceDraftKind:'PLAN',servicePlanSummary:plan&&plan.body&&plan.body.summary||'',servicePlanAdvice:plan&&plan.body&&plan.body.advice||'',serviceDraftId:plan&&plan.id||'',serviceDraftRevision:plan?plan.revision:null,serviceNote:''});},
 async saveServiceDraft(){const kind=this.data.serviceTab==='plan'?'PLAN':'REPLY';if(kind==='REPLY'&&!this.data.serviceDraftFeedbackId){this.setData({serviceError:'请先选择一条家长反馈'});return;}if(this.data.serviceDraftKind!==kind){this.setData({serviceError:'请先打开要编辑的草稿'});return;}const revision=this.data.serviceDraftRevision;const r=await this.serviceAction('SAVE_SERVICE_DRAFT',{appointmentId:this.serviceSelectedId,kind,feedbackId:this.data.serviceDraftFeedbackId,...(revision!=null?{revision}:{}),content:this.data.serviceInput,summary:this.data.servicePlanSummary,advice:this.data.servicePlanAdvice});if(r){this.setData({serviceDraftId:r.item.id,serviceDraftRevision:r.item.revision});await this.refreshServiceCase();wx.showToast({title:'草稿已保存',icon:'success'});}},
 async reviewServiceItem(e){const id=e.currentTarget.dataset.id,action=e.currentTarget.dataset.action;const item=[this.data.servicePlan,...this.data.serviceFeedback.map(f=>f.reply)].find(r=>r&&String(r.id)===String(id));if(!item)return;let availableAt;if(action==='APPROVE'&&item.stage==='GENERAL'){const hours=Number(this.data.serviceReleaseHours);if(!Number.isFinite(hours)||hours<0||hours>8760){this.setData({serviceError:'可见时间需填写0至8760小时'});return;}availableAt=new Date(Date.now()+hours*3600000).toISOString();}const r=await this.serviceAction('REVIEW_SERVICE_ITEM',{itemId:id,revision:item.revision,action,note:this.data.serviceNote,availableAt});if(r){await this.refreshServiceCase();wx.showToast({title:'处理完成',icon:'success'});}},
 async supplementServiceCase(){const plan=this.data.servicePlan;if(!plan)return;const r=await this.serviceAction('SUPPLEMENT_SERVICE_CASE',{appointmentId:this.serviceSelectedId,itemId:plan.id,revision:plan.revision,content:this.data.serviceInput});if(r){this.setData({serviceInput:''});await this.refreshServiceCase();}},
 async openServiceAssignment(){const r=await this.serviceAction('LIST_SERVICE_STAFF',{});if(!r)return;const guardians=r.items.filter(i=>i.service_kind!=='AGENT'),directors=r.items.filter(i=>i.review_role==='DIRECTOR');const a=this.data.serviceDetail.appointment;this.setData({serviceGuardians:guardians,serviceDirectors:directors,serviceGuardianIndex:Math.max(0,guardians.findIndex(i=>String(i.id)===String(a.guardian_id))),serviceDirectorIndex:Math.max(0,directors.findIndex(i=>String(i.id)===String(a.director_id))),serviceAssignOpen:true});},
 changeServiceAssignment(e){this.setData({[e.currentTarget.dataset.field]:Number(e.detail.value)});},
 changeServiceMeta(e){this.setData({['serviceMeta.'+e.currentTarget.dataset.field]:e.detail.value});},
 changeServicePriority(e){this.setData({'serviceMeta.priority':e.detail.value});},
 changeServiceMetaLevel(e){this.setData({'serviceMeta.level':this.data.serviceLevelOptions[Number(e.detail.value)]});},
 async saveServiceAssignment(){const g=this.data.serviceGuardians[this.data.serviceGuardianIndex],d=this.data.serviceDirectors[this.data.serviceDirectorIndex];if(!g||!d){this.setData({serviceError:'请先在管理端授权监护专员与总监，再分配'});return;}const r=await this.serviceAction('ASSIGN_SERVICE_CASE',{appointmentId:this.serviceSelectedId,previousUpdatedAt:this.data.serviceDetail.appointment.updated_at,guardianId:g.id,directorId:d.id,...this.data.serviceMeta});if(r){this.setData({serviceAssignOpen:false});await this.refreshServiceCase();}},
 openServiceArchive(){this.setData({serviceTab:'archive',serviceAssignOpen:false});},
 showLegacyServiceChat(){this.stopServiceChat();this.setData({serviceMode:false});},
 showServiceFeedback(){this.loadServiceChat();},
 openServicePermissions(){wx.navigateTo({url:'/pages/manager/manager?tab=identities'});}
};
module.exports={data,methods,decorate};
