// Render official WXML compiler output to a local browser layout review. This is not a native simulator.
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.codex-work/course-reference/ui');fs.mkdirSync(out,{recursive:true});
const wxRuntime={window:{},console};vm.createContext(wxRuntime);vm.runInContext(fs.readFileSync(path.join(root,'.codex-work/course-reference/wcc-compiled.js'),'utf8'),wxRuntime);
const c={id:11,title:'读懂孩子的情绪，让亲子沟通重新开始',description:'当孩子不愿说、父母忍不住追问时，我们如何走近彼此？这堂公开课，一起练习倾听，找到适合家庭的沟通方式。',status:'PUBLISHED',statusText:'报名中',starts_at:'2026-09-20T06:00:00.000Z',timeText:'2026-09-20 14:00',placeText:'成都 · 详细地址群内通知',deadlineText:'2026-09-19 18:00',capacity:30,reserved_count:18,seatsText:'剩余 12 / 30 个名额',city:'成都',notice:'请提前到场，向工作人员出示个人入场凭证。',canEnroll:true,group_guide:'工作人员会通过报名手机号联系你，邀请加入本场课程群。具体地址在群内通知，请留意群消息。',contact_phone:'13800000000'};
const entry={id:21,registrant_name:'合成家长',phone:'13800000000',phoneMasked:'138****0000',status:'REGISTERED',statusText:'已报名',attendanceText:'待参加/待核实',stateText:'待参加',attendance_status:'PENDING',group_status:'PENDING',groupText:'待联系',createdText:'2026-09-09 18:00',public_class_id:11,public_class:c,entry_code:'ABCDEFGHJKLMNPQRSTUVWXYZ2',entryPayload:'EMPATH-ENTRY:ABCDEFGHJKLMNPQRSTUVWXYZ2',canCancel:true};
const names=['public-class','public-class-detail','class-enroll','my-enrollments','class-ticket','course-manage','course-edit','course-roster','course-poster','customer','service-workbench'];
names.unshift('index','plaza','advisor','course-detail','consultation-detail');
const labels=['首页','原课程','专家介绍','原课程详情','咨询记录','课程列表','课程详情','报名确认','我的报名','入场凭证','课程管理','课程编辑','名单与核销','课程分享','客户中心','服务工作台'];
function css(file){return fs.readFileSync(file,'utf8').replace(/@import\s+["']([^"']+)["'];/g,(_,p)=>css(path.resolve(path.dirname(file),p)));}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
function render(node){if(node==null)return '';if(typeof node!=='object')return esc(node);let tag=(node.tag||'').replace(/^wx-/,'');if(['virtual','block','page',''].includes(tag))return (node.children||[]).map(render).join('');const a=node.attr||{};const mapped={view:'div',text:'span','scroll-view':'div',picker:'div',navigator:'div',image:'img'};tag=mapped[tag]||tag;if(node.tag==='wx-scroll-view')a.style=(a.style||'')+';overflow-x:auto';let attrs=Object.entries(a).filter(([k,v])=>['class','style','src','placeholder','value','disabled'].includes(k)&&v!==false).map(([k,v])=>k==='disabled'?'disabled':k+'="'+esc(v)+'"').join(' ');if(tag==='canvas'&&a.canvasId==='entry-code'){const cells=require('../utils/courseQr').matrix(entry.entryPayload);return '<svg class="ticket-canvas" viewBox="0 0 '+(cells.length+8)+' '+(cells.length+8)+'"><rect width="100%" height="100%" fill="white"/>'+cells.map((row,y)=>row.map((dark,x)=>dark?'<rect x="'+(x+4)+'" y="'+(y+4)+'" width="1" height="1" fill="#183b35"/>':'').join('')).join('')+'</svg>';}
return '<'+tag+' '+attrs+'>'+((node.children||[]).map(render).join(''))+(['input','img'].includes(tag)?'':'</'+tag+'>');}
const styles=css(path.join(root,'app.wxss'));
const original=require('../utils/mock');
const consultation=JSON.parse(fs.readFileSync(path.join(root,'.codex-work/course-reference/native-qa/scenarios.json'),'utf8')).find(s=>s.name==='consultation-parent').patch;
for(const name of names){let page;vm.runInNewContext(fs.readFileSync(path.join(root,'pages',name,name+'.js'),'utf8'),{Page:p=>page=p,require:m=>m.endsWith("/mock")?original:({})});const data={...page.data,...(name==='consultation-detail'?consultation:{}),statusBarHeight:44,navHeight:88,navPaddingRight:110,featuredAdvisors:original.advisors.map(a=>({...a,displayTags:a.tags.slice(0,2)})),advisor:original.advisors[0],userInfo:{nickName:'欢迎来到知守'},defaultPortrait:original.userPortrait,visibleCourses:original.courses,featuredCourse:original.courses[0],course:original.courses[0],loading:false,error:'',allowed:true,canAccept:true,isLoggedIn:true,loggedIn:true,isStaff:true,classInfo:c,enrollment:entry,classes:[c],items:[entry],enrollments:[entry],stats:{registered:18,attended:0,pending:18},success:true,form:{...page.data.form,title:c.title,description:c.description,date:'2026-09-20',time:'14:00',capacity:'30',city:'成都',groupGuide:c.group_guide}};
for(const mode of ['normal','empty','error','loading']){const d=mode==='normal'?data:mode==='error'?{...page.data,loading:false,error:'报名与咨询服务暂未开放，请稍后再试。'}:mode==='loading'?{...page.data,loading:true}:{...page.data,loading:false,allowed:true,isLoggedIn:true,loggedIn:true};const tree=wxRuntime.$gwx('pages/'+name+'/'+name+'.wxml')(d,{});let st=(styles+'\n'+css(path.join(root,'pages',name,name+'.wxss'))).replace(/(^|\n)page\s*\{/g,'$1body {').replace(/(-?[\d.]+)rpx/g,'calc($1 * 100vw / 750)').replace(/\bview\b/g,'div').replace(/\btext\b(?=\s*[\{,])/g,'span');fs.writeFileSync(path.join(out,name+'-'+mode+'.html'),'<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;font-family:-apple-system,sans-serif}button{font-family:inherit;border:0;box-sizing:border-box}input,textarea{font-family:inherit}img{object-fit:cover}'+st+'</style>'+render(tree)+'<script>window.addEventListener("load",()=>{const over=[...document.querySelectorAll("body *")].filter(e=>{const r=e.getBoundingClientRect();return !e.closest(".course-tabs,.hero-arch,.tag-scroll,.poster-canvas")&&r.left>=0&&r.right>innerWidth+1}).map(e=>e.className||e.tagName);parent.postMessage({page:'+JSON.stringify(name)+',mode:'+JSON.stringify(mode)+',width:innerWidth,overflow:over},"*")})</script>');}}
fs.writeFileSync(path.join(out,'index.html'),'<!doctype html><meta charset="utf-8"><style>body{font:15px system-ui;background:#e8e9e3;padding:20px;color:#173e35}header{display:flex;align-items:center;gap:20px}select{padding:12px}main{display:flex;gap:20px}iframe{height:820px;border:0;background:white;border-radius:16px}#status{font-size:12px}h2{font-size:16px}</style><header><h1>课程报名页面检查</h1><select id="page">'+names.map((n,i)=>'<option value="'+n+'">'+labels[i]+'</option>').join('')+'</select><select id="mode"><option value="normal">正常示例</option><option value="empty">空数据</option><option value="error">接口异常</option><option value="loading">加载中</option></select></header><p>合成展示数据 · 从实际 WXML/WXSS 生成的排版预览，非原生模拟器</p><p id="status"></p><main>'+[320,375,430].map(w=>'<section><h2>'+w+' px</h2><iframe width="'+w+'"></iframe></section>').join('')+'</main><script>let results=[];function show(){results=[];document.querySelectorAll("iframe").forEach(f=>f.src=page.value+"-"+mode.value+".html")}page.value=new URLSearchParams(location.search).get("page")||"public-class";mode.value=new URLSearchParams(location.search).get("mode")||"normal";page.onchange=mode.onchange=show;window.onmessage=e=>{if(e.data&&e.data.overflow){results.push(e.data);status.textContent=JSON.stringify(results);document.getElementById("status").textContent=results.map(r=>r.width+"px："+(r.overflow.length?"需检查 "+r.overflow.join(","):"无横向溢出")).join(" · ")}};show()</script>');
console.log('Generated '+names.length*4+' previews from official WXML output');
