let state,detail=null,selected=null,busy=false,lastSignature='',toastTimer;const app=document.querySelector('#app');const params=new URLSearchParams(location.search);const incoming=params.get('ref');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';const roleNames={MANAGER:'管理人员',AGENT:'代理',CUSTOMER:'客户'};
function toast(message){const n=document.querySelector('#toast');n.textContent=message;n.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.style.display='none',4000);}
async function request(url,payload){const r=await fetch(url,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.message||'请求失败');return data;}
async function act(operation,payload){return (await request('/api/action',{operation,payload})).data;}
function user(key){return state.users.find(u=>u.key===key);}
function input(name,label,value='',type='text'){return `<label><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" required></label>`;}
function qr(url){const q=qrcode(0,'M');q.addData(url);q.make();return `<div class="qr">${q.createImgTag(4,12,'演示链接二维码')}</div>`;}
function loginView(){return `<section class="hero"><div class="eyebrow">知守 · 三端联动演示</div><h1>${state.user.label}登录</h1><p>用同一套业务规则，体验不同身份的操作与数据归属。</p></section><section class="card login-card"><div class="identity"><div class="avatar">${state.user.name[0]}</div><div><h3>${esc(state.user.name)}</h3><small>后台账号 ${state.user.id} · 独立登录会话</small></div></div><div class="notice">使用独立的 Zion 测试账号登录。身份和数据权限均由项目后台判断，不会调用真实微信授权。</div><button class="primary" data-action="login">登录后台测试账号 →</button></section><div class="guide"><div class="step">管理人员指定代理身份</div><div class="step">管理员直接绑定客户，或代理分享后客户报名</div><div class="step">家长提交资料，工作人员整理并确认回复</div><div class="step">确认完成后 3 小时，客户查看反馈</div></div>`;}
function managerView(){const a=state.data.agents.find(a=>String(a.account_id)===String(user('agent').id)),active=a?.service_status==='ACTIVE',bound=state.data.customerBinding;return `<section class="card"><h2>01 / 代理身份管理</h2><p class="sub">管理人员指定后，该账号才能邀请和查看客户。</p><div class="row"><div><h3>${esc(user('agent').name)}</h3><small>账号 ${user('agent').id} · ${active?'代理已启用':'当前为普通客户'}</small></div><button data-action="designate" ${active?'disabled':''}>${active?'已指定代理':'指定为代理'}</button></div></section><section class="card"><h2>02 / 客户直接归属</h2><p class="sub">首次绑定后固定归属，不允许其他代理覆盖。</p><div class="row"><div><h3>${esc(user('customer').name)}</h3><small>${bound?'已归属 '+esc(user('agent').name):'尚未绑定推荐人'}</small></div><span class="badge">客户 ${user('customer').id}</span></div><button class="primary gold" data-action="bind" ${!active||bound?'disabled':''}>${bound?'客户归属已锁定':'将此客户绑定到 '+esc(user('agent').name)}</button><p class="muted" style="margin-top:12px">想看分享报名路径，可以跳过直接绑定，去代理端打开邀请链接。</p></section><section class="card"><h2>03 / 孩子资料与回复</h2>${state.data.intakes.length?state.data.intakes.map(r=>`<div class="row"><div><h3>${esc(r.child_name)}</h3><small>${esc(r.guardian_name)} · ${statusText(r)}</small></div><button class="ghost" data-action="detail" data-id="${r.id}">${r.feedback_status==='CONFIRMED'?'查看回复':'整理回复'}</button></div>`).join(''):'<div class="empty">等待客户报名并提交孩子资料</div>'}</section><section class="card"><h3>后台计时规则</h3><p class="muted">确认回复完成后，由 Zion 记录真实完成时间。3小时后客户才能查看，联调页面不能提前解锁。</p></section>`;}
function agentView(){if(!state.data.canInvite)return `<section class="card"><h2>等待指定代理身份</h2><p class="muted">请在管理人员页面点击“指定为代理”。这里会自动更新，无需重新登录。</p></section>`;const link=`http://localhost:${user('customer').port}/?ref=${state.user.id}`;return `<section class="card"><h2>我的邀请</h2><p class="sub">客户通过此链接报名成功后，归属固定在你名下。</p><div class="linkbox">${esc(link)}</div><div class="row"><a class="button" href="${link}" target="_blank" rel="noopener">打开客户邀请页 ↗</a><button class="ghost" data-action="copy" data-url="${link}">复制链接</button></div>${qr(link)}<p class="muted">本机链接用于这台电脑演示，手机扫码不能访问 localhost。</p></section><section class="card"><h2>我的客户 <span class="badge">${state.data.clients.length} 位</span></h2>${state.data.clients.length?state.data.clients.map(c=>`<div class="row"><div><h3>${esc(c.referred_account.wechat_nickname)}</h3><small>${c.source==='MANAGER_ASSIGNED'?'管理员直接绑定':'分享报名绑定'} · 归属已锁定</small><p class="muted">${c.referred_account.public_class_enrollments.length?'已报名公开课':'尚未报名'}</p></div><span class="badge">直属客户</span></div>`).join(''):'<div class="empty">暂时还没有客户<br>可以通过分享报名或管理员直接绑定。</div>'}<p class="muted" style="margin-top:15px">代理查看客户及报名状态；孩子详细资料由负责工作人员处理。</p></section>`;}
function statusText(r){return ({NOT_SUBMITTED:'待填写资料',PENDING:'等待工作人员整理',DRAFT:'工作人员整理中',CONFIRMED:'回复已确认完成'})[r.feedback_status]||'待填写资料';}
function customerView(){const binding=state.data.binding,e=state.data.enrollments.items.find(x=>String(x.public_class_id)===String(state.classId));return `<section class="card"><h2>我的推荐人</h2>${binding?`<div class="row"><div><h3>${esc(binding.referrer.wechat_nickname||binding.referrer.username)}</h3><small>绑定时间 ${fmt(binding.locked_at)}</small></div><span class="badge">归属已锁定</span></div>`:`<p class="muted">${incoming?'你正在通过代理邀请链接访问，报名成功后确定归属。':'尚无推荐人。可由管理员直接绑定，或通过代理邀请报名。'}</p>`}</section><section class="card"><div class="eyebrow">知守 · 公开课堂</div><h2 style="margin-top:8px">父母有道，孩子有路</h2>${!e?`<form id="enroll" class="stack">${input('registrant','报名姓名',state.user.name)}${input('phone','联系电话（模拟）','13800000000','tel')}<button class="primary gold">免费公开课报名 →</button></form>`:`<div class="notice good">报名成功 · 报名编号 ${e.id}</div><p class="muted" style="margin-top:15px">${statusText(e)}</p><button class="primary" data-action="detail" data-id="${e.id}">${e.child_submitted_at?'查看孩子资料与反馈':'填写孩子资料'}</button><div class="linkbox">http://localhost:${state.user.port}/?intake=${e.id}</div>${qr(`http://localhost:${state.user.port}/?intake=${e.id}`)}<p class="muted">二维码进入本人的资料页，仍需要登录。此处为本机演示链接。</p>`}</section>`;}
function detailView(){if(!detail)return '';const r=detail.intake;const reviewing=r.canReview;let html=`<section class="card" id="intake-panel"><div class="row"><h2>${reviewing?'工作人员梳理':'孩子资料与反馈'}</h2><button class="text-button" data-action="close">收起</button></div>`;
 if(!r.child_submitted_at&&!reviewing){html+=`<p class="sub">请使用模拟资料，选择你认为最重要的两个问题。</p><form id="child" class="stack"><div class="cols">${input('name','孩子姓名','小禾（模拟）')}<label><span>性别</span><select name="gender"><option>男</option><option selected>女</option><option>不便透露</option></select></label>${input('age','年龄','12','number')}${input('grade','年级','六年级')}</div>${input('economicSource','孩子经济来源','父母供养')}<div><span>问题选项（只能选择最重要的两个）</span><div class="checkgrid" style="margin-top:10px">${detail.issues.map((v,i)=>`<label class="choice"><input type="checkbox" name="issues" value="${esc(v)}" ${i<2?'checked':''}>${esc(v)}</label>`).join('')}</div></div><label><span>问题描述（可自行填写）</span><textarea name="description">模拟：孩子最近不太愿意和家长谈学习，希望先理解孩子的感受。</textarea></label><label><span>日常表现</span><textarea name="dailyBehavior" required>模拟：放学后喜欢独处，周末会和朋友打球。</textarea></label><div class="cols">${input('guardianName','家长姓名',state.user.name)}${input('guardianPhone','联系电话','13800000000','tel')}</div><label class="consent"><input type="checkbox" name="consent" required>我确认以监护人身份提交这份模拟资料，供负责工作人员整理反馈。</label><button class="primary">提交孩子资料</button></form>`;}
 else{html+=`<div class="notice">${statusText(r)}</div><dl class="detail">${[['姓名',r.child_name],['性别 / 年龄',`${r.child_gender} / ${r.child_age} 岁`],['年级',r.child_grade],['经济来源',r.child_economic_source],['最重要的问题',(r.child_issues||[]).join('、')],['问题描述',r.child_description||'未填写'],['日常表现',r.child_daily_behavior],['家长 / 电话',`${r.guardian_name} / ${r.guardian_phone}`]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;
 if(reviewing&&r.feedback_status!=='CONFIRMED')html+=`<form id="feedback"><label><span>工作人员梳理反馈</span><textarea name="content" rows="7" required>${esc(r.feedback_content||'【模拟工作人员反馈】\n建议先和孩子约定一段不谈成绩的交流时间，倾听孩子对近期学习和生活的感受。结合家长选择的两项问题，逐步记录具体情境，再与工作人员讨论适合家庭的沟通方式。')}</textarea></label><p class="muted">保存草稿不会启动计时；确认完成后，家长再等待3小时查看。</p><div class="row" style="margin-top:16px"><button class="ghost" name="confirm" value="false">保存草稿</button><button name="confirm" value="true">确认回复完成</button></div></form>`;
 else if(r.feedback_status==='CONFIRMED'){html+=`<p class="muted">确认完成：${fmt(r.feedback_confirmed_at)}<br>可查看时间：${fmt(r.feedback_available_at)}</p>`;if(r.canViewFeedback||reviewing)html+=`<div class="feedback">${esc(r.feedback_content)}</div>${reviewing&&!r.canViewFeedback?'<p class="muted">此正文仅工作人员可见，客户仍在等待。</p>':''}`;else html+='<div class="empty">回复已完成，等待3小时开放<br>等待期间后台不会向客户返回反馈正文。</div>';}
 else html+='<p class="muted">资料已提交，等待工作人员整理。确认回复完成后，再过3小时可查看。</p>';}
 return html+'</section>';}
function render(force=false){if(!state)return;if(state.backend!=='ZION'){app.innerHTML='<section class="hero"><div class="eyebrow">知守 · 后台联调</div><h1>正在接入实际项目后台</h1><p>原本机模拟已暂停。正在配置三个真实测试账号、代理身份和客户归属。</p></section>';return;}if(!force&&['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const key=JSON.stringify([state.loggedIn,state.data,state.events,state.clockOffset,detail&&{...detail,intake:{...detail.intake,serverNow:null}}]);if(!force&&key===lastSignature)return;lastSignature=key;
 document.title=`${state.user.label} · 知守流程演示`;app.innerHTML=`<header><span class="brand">知守<span class="eyebrow"> / ${state.user.label}端</span></span>${state.loggedIn?'<button class="text-button" data-action="logout">退出登录</button>':'<span class="badge">后台账号登录</span>'}</header>${!state.loggedIn?loginView():`<section class="hero"><div class="eyebrow">${roleNames[state.data.role]}工作台</div><h1>${esc(state.user.name)}</h1><p>${state.user.key==='manager'?'指定身份、确认归属，跟进每一份反馈。':state.user.key==='agent'?'从一份邀请开始，陪伴每一个家庭。':'了解孩子，从一次认真倾听开始。'}</p><span class="badge"><span class="state-dot"></span>已登录 · ${roleNames[state.data.role]}</span></section>${state.user.key==='manager'?managerView():state.user.key==='agent'?agentView():customerView()}${detailView()}<section class="card"><h2>三端联动记录</h2><p class="sub">业务记录写入 Zion 项目数据库，三个页面自动同步。</p><ol class="timeline">${state.events.map(e=>`<li>${esc(e.actor)} · ${esc(e.operation)}<time>${fmt(e.at)}</time></li>`).join('')}</ol></section>`}<div class="links">${state.users.map(u=>`<a href="http://localhost:${u.port}" target="_blank" rel="noopener">${u.label}端 ↗</a>`).join('')}</div><p class="muted" style="margin-top:14px">本次使用独立测试账号与 Zion 项目数据库联调；公众号微信授权需在正式微信环境验收。</p>`;}
async function refresh(force=false){try{state=await request('/api/state');document.querySelector('.demo-bar').textContent=state.backend==='ZION'?'Zion 项目后台 · 三个独立测试账号 · 真实数据读写':'正在切换项目后台；原本机演示尚未接入 Zion';if(state.loggedIn&&selected)detail=await act('GET_CHILD_INTAKE',{enrollmentId:selected});render(force);}catch(e){toast(e.message);}}
async function work(fn){if(busy)return;busy=true;try{await fn();await refresh(true);}catch(e){toast(e.message);}finally{busy=false;}}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;work(async()=>{const a=b.dataset.action;if(a==='login')await request('/api/login',{});if(a==='logout'){await request('/api/logout',{});selected=null;detail=null;}if(a==='designate'){await act('SET_AGENT',{accountId:user('agent').id,active:true});toast('代理身份已指定，请查看代理端');}if(a==='bind'){await act('BIND_CUSTOMER',{customerId:user('customer').id,agentAccountId:user('agent').id});toast('客户归属已存入数据库');}if(a==='detail')selected=Number(b.dataset.id);if(a==='close'){selected=null;detail=null;}if(a==='copy'){await navigator.clipboard.writeText(b.dataset.url);toast('已复制邀请链接');}});});
app.addEventListener('change',e=>{if(e.target.name==='issues'&&app.querySelectorAll('[name="issues"]:checked').length>2){e.target.checked=false;toast('只能选择最重要的两个问题');}});
app.addEventListener('submit',e=>{e.preventDefault();const f=e.target,fd=new FormData(f),values=Object.fromEntries(fd);work(async()=>{if(f.id==='enroll'){const data=await act('ENROLL',{classId:state.classId,name:values.registrant,phone:values.phone,...(incoming?{referrerId:incoming}:{})});selected=data.enrollment.id;toast('报名成功，可以填写孩子资料');}if(f.id==='child'){if(fd.getAll('issues').length!==2)throw Error('请选择最重要的两个问题');await act('SUBMIT_CHILD_INTAKE',{...values,enrollmentId:selected,age:Number(values.age),issues:fd.getAll('issues'),consent:values.consent==='on'});toast('资料已提交');}if(f.id==='feedback'){const confirm=e.submitter?.value==='true';await act('SAVE_CHILD_FEEDBACK',{enrollmentId:selected,revision:detail.intake.feedback_revision,content:values.content,confirm});toast(confirm?'回复已确认完成，3小时后客户可查看':'草稿已保存，尚未启动计时');}});});
selected=params.has('intake')?Number(params.get('intake')):null;refresh(true);setInterval(()=>{if(!busy)refresh();},5000);
