const service=require('../../utils/consultationService');const auth=require('../../utils/auth');const {enrollmentCard,classCard}=require('../../utils/coursePresentation');
Page({data:{loading:true,busy:false,error:'',allowed:false,classInfo:null,items:[],stats:{},search:'',filter:'ALL',nextCursor:null,scanCandidate:null,tabs:[{key:'ALL',label:'全部报名'},{key:'CONTACT',label:'待联系'},{key:'JOINED',label:'已进群'},{key:'PENDING',label:'待到课'},{key:'ATTENDED',label:'已到课'},{key:'ABSENT',label:'未到课'},{key:'CANCELED',label:'已取消'}]},
 onLoad(q={}){this.classId=q.id||'';},onShow(){this.refresh();},refresh(){return this.load(false);},more(){return this.load(true);},inputSearch(e){this.setData({search:e.detail.value});},filter(e){if(this.fetching)return;this.setData({filter:e.currentTarget.dataset.key});this.refresh();},
 async load(more){if(more && this.appliedSearch!==this.data.search)more=false;if(this.fetching){if(!more)this.pendingSearch=true;return;}if(!auth.requireLogin('请登录本场课程的工作人员账号。')){this.setData({loading:false,allowed:false});return;}this.fetching=true;this.setData({loading:true,error:''});try{const search=this.data.search;const r=await service.call('COURSE_ROSTER',{classId:this.classId,search:search,filter:this.data.filter,cursor:more?this.data.nextCursor:null});this.appliedSearch=search;this.setData({allowed:true,classInfo:classCard(r.classInfo),stats:r.stats,items:(more?this.data.items:[]).concat((r.items||[]).map(enrollmentCard)),nextCursor:r.nextCursor});}catch(e){if(!more)this.setData({allowed:false,items:[]});service.error(this,e);}finally{this.fetching=false;this.setData({loading:false});if(this.pendingSearch){this.pendingSearch=false;this.refresh();}}},
 scan(){if(this.data.busy)return;wx.scanCode({onlyFromCamera:true,scanType:['qrCode'],success:async r=>{this.setData({busy:true,error:'',scanCandidate:null});try{const out=await service.call('LOOKUP_ENTRY',{classId:this.classId,entryCode:r.result});this.scanValue=r.result;this.setData({scanCandidate:enrollmentCard(out.enrollment)});}catch(e){service.error(this,e);}finally{this.setData({busy:false});}},fail:e=>{if(!/cancel/.test(e.errMsg||''))this.setData({error:'无法扫码，请允许相机权限或在名单中人工核实。'});}});},
 closeScan(){this.scanValue=null;this.setData({scanCandidate:null});},
 confirmScan(){if(this.data.busy||!this.scanValue)return;const code=this.scanValue;wx.showModal({title:'确认实际到课',content:'请核对报名人确实参加本场公开课。确认后将开放线下咨询申请资格。',success:r=>{if(r.confirm)this.perform('CHECK_IN',{entryCode:code});}});},
 verify(e){if(this.data.busy)return;const {id,field,value}=e.currentTarget.dataset;if(field==='attendanceStatus'){wx.showModal({title:'核实参加情况',content:value==='ATTENDED'?'确认此人实际参加了本场公开课？确认后可申请线下咨询。':'确认此人未到课？',success:r=>{if(r.confirm)this.perform('VERIFY_ENROLLMENT',{enrollmentId:id,[field]:value});}});}else this.perform('VERIFY_ENROLLMENT',{enrollmentId:id,[field]:value});},
 async perform(op,p){this.setData({busy:true,error:''});try{const r=await service.call(op,{...p,classId:this.classId});this.closeScan();wx.showToast({title:r.alreadyCheckedIn?'已核销，无需重复':'已更新',icon:'success'});await this.refresh();}catch(e){service.error(this,e);}finally{this.setData({busy:false});}},
 call(e){wx.makePhoneCall({phoneNumber:e.currentTarget.dataset.phone});}
});
