(function(){
  const state={loggedIn:false,user:null,courses:[],enrollments:[],referrals:[],referralToken:"",referralBinding:null,canManage:false,managerClasses:[]};
  const $=(selector,root=document)=>root.querySelector(selector);
  const $$=(selector,root=document)=>Array.from(root.querySelectorAll(selector));
  const isWechat=/MicroMessenger/i.test(navigator.userAgent);
  let toastTimer;

  function toast(message){const box=$("#toast");box.textContent=message;box.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove("show"),2600)}
  function escapeHtml(value){return String(value==null?"":value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function formatDate(value){if(!value)return "时间待通知";const d=new Date(value);if(Number.isNaN(d.getTime()))return "时间待通知";return new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(d)}
  function statusText(enrollment){if(enrollment.status==="CANCELED")return "已取消";if(enrollment.attendance_status==="ATTENDED")return "已到课";return "已报名"}
  async function api(action,options={}){const response=await fetch(`/api/h5?action=${encodeURIComponent(action)}${options.query||""}`,{method:options.method||"GET",headers:options.body?{"content-type":"application/json"}:{},body:options.body?JSON.stringify(options.body):undefined,credentials:"same-origin"});const data=await response.json().catch(()=>({ok:false,message:"服务返回异常"}));if(!response.ok||!data.ok)throw new Error(data.message||"请求失败");return data.data}
  function login(){if(!isWechat){toast("请复制当前链接，在微信内打开后登录");return}const ref=new URLSearchParams(location.search).get("ref")||"";location.href=`/api/h5?action=login&ref=${encodeURIComponent(ref)}&return=${encodeURIComponent(location.pathname+location.search+location.hash)}`}
  function nav(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.bottom-nav button').forEach(b=>{const active=b.dataset.nav===name;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')});location.hash=name==='home'?"":name;window.scrollTo({top:0,behavior:"smooth"})}
  function previewCourse(){openCourse({id:"preview",title:"《透过现象·直击本质》二阶线上共修营·03期",description:"在《父母学习·孩子蜕变》一阶共修结束后，面向希望深度精进的家庭继续开展二阶共修。\n\n课程以同伴共学为根基、落地实操为核心、根源纠偏为路径、长效培优为目标，帮助家长跳出治标式处理，从根源看懂并改善长期育儿卡点。",status:"PREVIEW",starts_at:null,canEnroll:false,closedReason:"具体开营时间与报名入口待完善",notice:"仅限完成《父母学习·孩子蜕变》一阶共修营的学员自愿报名。\n营期开启后不再接收新增学员；线上会议室迟到15分钟将无法进入当期课堂；每日双时段学习；导师实时带学，学员需完成每日打卡。"})}
  function isPreview(course){return Boolean(course&&course.preview)||String(course&&course.id)==='preview'}
  function coverUrl(course){const value=String(course&&course.cover&&course.cover.url||'');return /^https:\/\//.test(value)?value:''}
  function publicCourseCard(course,variant){const compact=variant==='home',cover=coverUrl(course),visual=cover?`<span class="${compact?'public-course-poster':'course-poster'}"><img src="${escapeHtml(cover)}" alt="${escapeHtml(course.title)}课程海报"></span>`:(compact?`<span class="public-course-card-top"><span>${escapeHtml(course.city||'公开课程')}</span></span>`:`<span class="course-thumb free-thumb"><small>${escapeHtml(course.city||'公开课程')}</small></span>`);return `<button class="${compact?'public-course-card':'course-row'}" type="button" data-course-id="${escapeHtml(course.id)}">${visual}<span class="${compact?'public-course-card-copy':''}">${compact&&cover?`<span class="public-course-card-top"><span>${escapeHtml(course.city||'公开课程')}</span></span>`:''}<h3>${escapeHtml(course.title)}</h3><p>${escapeHtml(formatDate(course.starts_at))}${course.city?` · ${escapeHtml(course.city)}`:''}</p><p class="course-price">报名 · ${course.canEnroll?'可直接报名':'报名暂未开放'}</p></span></button>`}
  function bindCourseCards(){$$('[data-course-id]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.courseId;if(id==='preview')previewCourse();else openCourse(state.courses.find(c=>String(c.id)===id))}))}
  function renderFreeCourseGrid(rows){const grid=$("#freeCourseGrid");if(!grid)return;const visible=rows.slice(0,3);grid.innerHTML=visible.length?visible.map(c=>publicCourseCard(c,'home')).join(''):'<p class="empty public-empty">公开课程发布后会在这里显示，可直接报名。</p>'}
  function renderCourses(){const q=$("#courseSearch").value.trim().toLowerCase();const rows=state.courses.filter(c=>`${c.title||""} ${c.city||""}`.toLowerCase().includes(q));const preview={id:"preview",title:"《透过现象·直击本质》二阶线上共修营·03期",starts_at:null,city:"线上共修",preview:true};$("#courseList").innerHTML=rows.length?rows.map(c=>publicCourseCard(c,'list')).join(''):'<p class="empty">暂时没有匹配的公开课程。</p>';$("#advancedCourseList").innerHTML=`<button class="course-row advanced-row" type="button" data-course-id="preview"><span class="course-thumb"><b>付费</b><small>线上共修</small></span><span><h3>${preview.title}</h3><p>内容待完善 · 报名即将开放</p></span></button>`;renderFreeCourseGrid(state.courses);bindCourseCards()}
  function openCourse(course){if(!course)return;const preview=isPreview(course);const pricing=preview?'<ul class="rules"><li>自愿参与，不影响已有课程与指导权益</li></ul>':'<ul class="rules"><li>填写姓名与手机号即可报名</li><li>课程地址与入场信息将在课程通知中发送</li></ul>';const enrolled=state.enrollments.find(e=>String(e.public_class_id)===String(course.id)&&e.status==='REGISTERED');const cover=preview?'《答案库》系列课程':'公开课',poster=coverUrl(course),detailVisual=poster?`<div class="detail-poster"><img src="${escapeHtml(poster)}" alt="${escapeHtml(course.title)}课程海报"></div>`:`<div class="detail-cover">${cover}</div>`;const eyebrow=preview?'知守 · 共修课堂 · 付费':'知守 · 公开课';$("#courseDetail").innerHTML=`<article class="detail">${detailVisual}<p class="eyebrow dark">${eyebrow}</p><h2>${escapeHtml(course.title)}</h2><p class="meta">${escapeHtml(formatDate(course.starts_at))}${course.city?` · ${escapeHtml(course.city)}`:""}</p><div class="description">${escapeHtml(course.description||"课程内容待完善")}</div><h3>学习与报名说明</h3><div class="description">${escapeHtml(course.notice||"走进课堂，一起练习倾听与沟通。")}</div>${pricing}<div class="detail-actions"><button class="primary-button" type="button" data-enroll ${course.canEnroll&&!enrolled?"":"disabled"}>${enrolled?"已报名 · 请到我的课程查看":course.canEnroll?preview?'微信登录并报名':'微信登录并报名':escapeHtml(course.closedReason||"报名暂未开放")}</button></div></article>`;const button=$("[data-enroll]",$("#courseDetail"));if(button&&!button.disabled)button.addEventListener('click',()=>startEnroll(course));$("#courseDialog").showModal()}
  function startEnroll(course){if(!state.loggedIn){$("#courseDialog").close();login();return}$("#courseDialog").close();$("#enrollForm [name=classId]").value=course.id;const preview=isPreview(course);const fee=$("#enrollFee");fee.hidden=preview;$("#enrollNote").textContent=preview?'提交后可在“我的”查看报名状态和课程通知。':'本场为公开课，提交后可在“我的”查看报名状态和课程通知。';$("button[type=submit]",$("#enrollForm")).textContent=preview?'提交报名信息':'确认报名';$("#enrollDialog").showModal()}
  function renderManager(){const section=$("#managerSection");section.hidden=!state.canManage;if(!state.canManage)return;const list=$("#managerCourseList");list.innerHTML=state.managerClasses.length?state.managerClasses.map(c=>`<article class="manager-course-card"><header><h3>${escapeHtml(c.title)}</h3><span class="status">${escapeHtml(c.status==='PUBLISHED'?'报名开放':'已结束')}</span></header><p>${escapeHtml(formatDate(c.starts_at))}${c.city?` · ${escapeHtml(c.city)}`:''}</p><footer><span>已报名 <strong>${Number(c.reserved_count||0)}</strong>${Number(c.capacity)?` / ${Number(c.capacity)} 人`: ' 人'}</span><button class="roster-button" type="button" data-roster-id="${escapeHtml(c.id)}">查看报名名单</button></footer></article>`).join(''):'<p class="empty">还没有已发布的公开课程。</p>';$$('[data-roster-id]',list).forEach(button=>button.addEventListener('click',()=>openRoster(button.dataset.rosterId)))}
  async function refreshManager(){if(!state.canManage)return;const data=await api('staff');state.managerClasses=data.classes||[];renderManager()}
  async function openRoster(classId){try{const data=await api('roster',{query:`&classId=${encodeURIComponent(classId)}`});const stats=data.stats||{},items=data.items||[];$("#rosterContent").innerHTML=`<p class="eyebrow dark">报名名单</p><h2>${escapeHtml(data.classInfo&&data.classInfo.title||'本场课程')}</h2><div class="roster-summary"><div><strong>${Number(stats.registered||0)}</strong><span>有效报名</span></div><div><strong>${Number(stats.pending||0)}</strong><span>待核实</span></div><div><strong>${Number(stats.attended||0)}</strong><span>已到课</span></div></div><div class="plain-list">${items.length?items.map(item=>`<article class="roster-person"><strong>${escapeHtml(item.registrant_name)}</strong><span>${escapeHtml(item.phone)} · ${escapeHtml(item.attendance_status==='ATTENDED'?'已到课':'待核实')}</span></article>`).join(''):'<p class="empty">暂时没有报名记录。</p>'}</div>`;$("#rosterDialog").showModal()}catch(error){toast(error.message)}}
  async function publishManagerCourse(event){event.preventDefault();const form=new FormData(event.currentTarget),title=String(form.get('title')||'').trim(),groupGuide=String(form.get('groupGuide')||'').trim(),startsAt=String(form.get('startsAt')||'');if(!title||!groupGuide||!startsAt){toast('请填写课程名称、开课时间和进群指引');return}const submit=$("button[type=submit]",event.currentTarget);submit.disabled=true;submit.textContent='正在发布…';try{await api('saveClass',{method:'POST',body:{title,description:String(form.get('description')||'').trim(),city:String(form.get('city')||'').trim(),startsAt,registrationClosesAt:String(form.get('registrationClosesAt')||''),capacity:String(form.get('capacity')||'0'),groupGuide,notice:String(form.get('notice')||'').trim()}});event.currentTarget.reset();$("#managerCourseDialog").close();await refreshManager();Object.assign(state,await api('bootstrap'));renderCourses();renderMine();renderManager();toast('公开课已发布')}catch(error){toast(error.message)}finally{submit.disabled=false;submit.textContent='发布课程'}}
  function renderMine(){const button=$("#loginButton");button.textContent=state.loggedIn?(state.user.name||"我的"):"微信登录";$("#profileName").textContent=state.loggedIn?(state.user.name||"微信用户"):"微信登录后查看";$("#profileLogin").hidden=state.loggedIn;if(state.loggedIn&&state.user.avatarUrl){$("#profileAvatar").outerHTML=`<img id="profileAvatar" src="${escapeHtml(state.user.avatarUrl)}" alt="用户头像" referrerpolicy="no-referrer">`}$("#enrollmentList").innerHTML=state.loggedIn?(state.enrollments.length?state.enrollments.map(e=>`<article class="list-card"><header><strong>${escapeHtml(e.public_class&&e.public_class.title||"课程")}</strong><span class="status">${statusText(e)}</span></header><p>${escapeHtml(formatDate(e.public_class&&e.public_class.starts_at))}</p>${e.status==='REGISTERED'?`<p>报名姓名：${escapeHtml(e.registrant_name||"")}</p>`:""}</article>`).join(""):'<p class="empty">暂无报名记录。</p>'):'<p class="empty">登录后可查看报名与入场信息。</p>';$("#referralCount").textContent=`${state.referrals.length}人`;$("#referralList").innerHTML=state.loggedIn?(state.referrals.length?state.referrals.map(r=>{const u=r.referred_account||{};const enrollments=u.public_class_enrollments||[];const active=enrollments.filter(e=>e.status==='REGISTERED');return `<article class="list-card"><header><strong>${escapeHtml(u.wechat_nickname||u.username||"微信用户")}</strong><span class="status">${active.length?`已报名 ${active.length} 门`:"暂未报名"}</span></header><p>推荐关系锁定于 ${escapeHtml(formatDate(r.locked_at||r.created_at))}</p>${active.map(e=>`<p>${escapeHtml(e.public_class&&e.public_class.title||"课程")} · ${statusText(e)}</p>`).join("")}</article>`}).join(""):'<p class="empty">还没有好友通过你的链接登录。</p>'):'<p class="empty">登录后可查看推荐记录。</p>';const note=$("#bindingNote");note.hidden=!state.referralBinding;if(state.referralBinding){const r=state.referralBinding.referrer||{};note.textContent=`你的推荐人已锁定为：${r.wechat_nickname||r.username||"微信用户"}`}}
  async function shareReferral(){if(!state.loggedIn){login();return}const url=new URL('/web/',location.origin);url.searchParams.set('ref',state.referralToken);const data={title:'知守共修课程',text:'邀请你一起学习知守家庭教育共修课程',url:url.toString()};try{if(navigator.share){await navigator.share(data);return}await navigator.clipboard.writeText(data.url);toast('专属推荐链接已复制')}catch(error){if(error.name!=='AbortError')toast('请长按复制浏览器地址后分享')}}
  async function boot(){const query=new URLSearchParams(location.search);if(query.get('loginError'))toast(query.get('loginError'));try{Object.assign(state,await api('bootstrap'));renderCourses();renderMine();renderManager()}catch(error){toast(error.message);renderCourses();renderMine();renderManager()}}
  $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$$('[data-preview-course]').forEach(b=>b.addEventListener('click',previewCourse));$("#loginButton").addEventListener('click',()=>state.loggedIn?nav('mine'):login());$("#profileLogin").addEventListener('click',login);$("#shareButton").addEventListener('click',shareReferral);$("#managerNewCourse").addEventListener('click',()=>$("#managerCourseDialog").showModal());$("#managerCourseForm").addEventListener('submit',publishManagerCourse);$("#courseSearch").addEventListener('input',renderCourses);$("#enrollForm").addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const phone=String(form.get('phone')||'').trim();if(!/^1[3-9][0-9]{9}$/.test(phone)){toast('请填写有效的11位手机号');return}const submit=$("button[type=submit]",event.currentTarget);const defaultLabel=submit.textContent;submit.disabled=true;submit.textContent='正在提交…';try{await api('enroll',{method:'POST',body:{classId:form.get('classId'),name:String(form.get('name')||'').trim(),phone}});$("#enrollDialog").close();toast('报名已提交');Object.assign(state,await api('bootstrap'));renderCourses();renderMine();renderManager();nav('mine')}catch(error){toast(error.message)}finally{submit.disabled=false;submit.textContent=defaultLabel}});window.addEventListener('hashchange',()=>nav(location.hash.slice(1)||'home'));nav(location.hash.slice(1)||'home');boot();
})();
